package api

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"gitee.com/yangdadayyds/uepcap/internal/job"
	"gitee.com/yangdadayyds/uepcap/internal/packet"
	"gitee.com/yangdadayyds/uepcap/internal/tshark"
)

// FlowBriefRequest represents the request for flow brief
type FlowBriefRequest struct {
	Filter string `json:"filter"`
}

// FlowBriefResponse represents the brief summary of filtered packets
type FlowBriefResponse struct {
	PacketCount      int                  `json:"packet_count"`
	TimeRange        *TimeRange           `json:"time_range,omitempty"`
	ProtocolsPresent []string             `json:"protocols_present"`
	KeyParams        *KeyParamsCandidates `json:"key_params"`
}

// TimeRange represents the time span of packets
type TimeRange struct {
	Start         string  `json:"start"`          // absolute time
	End           string  `json:"end"`            // absolute time
	DurationMs    float64 `json:"duration_ms"`    // duration in milliseconds
	StartRelative string  `json:"start_relative"` // relative time
	EndRelative   string  `json:"end_relative"`   // relative time
}

// KeyParamsCandidates holds key parameters extracted from packets
type KeyParamsCandidates struct {
	IMSI        []string `json:"imsi,omitempty"`
	SUPI        []string `json:"supi,omitempty"`
	UEIP        []string `json:"ue_ip,omitempty"`
	TEID        []string `json:"teid,omitempty"`
	SEID        []string `json:"seid,omitempty"`
	QFI         []string `json:"qfi,omitempty"`
	RanUeNgapID []string `json:"ran_ue_ngap_id,omitempty"`
	AmfUeNgapID []string `json:"amf_ue_ngap_id,omitempty"`
}

// FlowGenerateRequest represents the request for flow generation
type FlowGenerateRequest struct {
	Filter    string `json:"filter"`
	MaxEvents int    `json:"max_events,omitempty"` // max events to send to LLM (default 200)
}

// FlowGenerateResponse represents the response with Mermaid diagram
type FlowGenerateResponse struct {
	FlowName  string               `json:"flow_name"`
	Mermaid   string               `json:"mermaid"`
	KeyParams *KeyParamsCandidates `json:"key_params,omitempty"`
	// Details is the mapping from Mermaid autonumber index to original packet frame.number.
	// Frontend uses this to correlate diagram messages with input packets.
	Details []FlowMessageDetail `json:"details,omitempty"`
	// InputJSON is the original compact packet JSON sent to LLM (for frontend to derive rich details).
	InputJSON string `json:"input_json,omitempty"`
	// Annotations contains LLM-provided IP→NE mapping and stage segmentation.
	// May be nil if LLM parsing failed (diagram still generated deterministically by Go).
	Annotations *FlowAnnotationsV1 `json:"annotations,omitempty"`
	// PacketColumns contains tshark-extracted column info (Protocol, Info, etc.) for each frame.
	// Used by frontend to display message labels and packet details without LLM parsing.
	PacketColumns map[string]*tshark.PacketColumns `json:"packet_columns,omitempty"`
}

// FlowMessageDetail maps a Mermaid message (by autonumber index) to the original packet.
// idx: 1-based message order in the Mermaid diagram (matches autonumber order).
// frame: 1-based input packet index (position in the input JSON array).
// originNumber: the original capture frame.number from pcap (Wireshark frame number).
type FlowMessageDetail struct {
	Idx          int    `json:"idx"`
	Frame        int    `json:"frame,omitempty"`
	OriginNumber string `json:"originNumber,omitempty"` // original pcap frame.number
}

// FlowFinalEvent is sent to the frontend via SSE after the LLM stream completes.
// It guarantees that the Mermaid and details_map are consistent with the exact input_json
// that was sent to the LLM (and sent to the web).
type FlowFinalEvent struct {
	FlowName string               `json:"flow_name"`
	Mermaid  string               `json:"mermaid"`
	Details  []FlowMessageDetail  `json:"details_map"`
	Mode     string               `json:"mode"` // "go_deterministic" (always now)
	Reasons  []string             `json:"reasons,omitempty"`
	Stats    *FlowValidationStats `json:"stats,omitempty"`
	// Annotations contains LLM-provided IP→NE mapping and stage segmentation.
	// May be nil if LLM parsing failed.
	Annotations *FlowAnnotationsV1 `json:"annotations,omitempty"`
	// PacketColumns contains tshark-extracted column info (Protocol, Info, etc.) for each frame.
	// Used by frontend to display message labels and packet details without LLM parsing.
	PacketColumns map[string]*tshark.PacketColumns `json:"packet_columns,omitempty"`
}

type FlowValidationStats struct {
	InputPackets      int `json:"input_packets"`
	MermaidMessages   int `json:"mermaid_messages"`
	MappingEntries    int `json:"mapping_entries"`
	RemovedHeartbeats int `json:"removed_heartbeats"`
}

// FlowAnnotationsV1 is the structured JSON returned by LLM for IP→NE mapping and stage segmentation.
// The Mermaid diagram is always generated by Go; LLM only provides these annotations.
type FlowAnnotationsV1 struct {
	Version  string      `json:"version"` // should be "flow_annotations_v1"
	FlowName string      `json:"flow_name,omitempty"`
	IPMap    []IPMapping `json:"ip_map"`
	Stages   []FlowStage `json:"stages"`
}

// IPMapping maps an IP address to a network element role.
type IPMapping struct {
	IP         string  `json:"ip"`
	NE         string  `json:"ne"`                   // gNB, AMF, SMF, UPF, SGW, PGW, Unknown, etc.
	Confidence float64 `json:"confidence,omitempty"` // 0.0-1.0, optional
	Reason     string  `json:"reason,omitempty"`     // optional explanation
}

// FlowStage represents a logical stage/phase in the signaling flow.
// Each stage contains an explicit list of frames (packets) that belong to it.
type FlowStage struct {
	Name       string           `json:"name"`
	Frames     []FlowStageFrame `json:"frames"` // explicit list of frames in this stage
	Summary    string           `json:"summary,omitempty"`
	Confidence float64          `json:"confidence,omitempty"`
}

// FlowStageFrame represents a single frame within a stage.
// Number corresponds to frame.number from input JSON (Wireshark frame number).
type FlowStageFrame struct {
	Number string `json:"number"`          // frame.number from input JSON
	Title  string `json:"title,omitempty"` // message name for Mermaid label
	Note   string `json:"note,omitempty"`  // operation/effect description for Mermaid Note
}

// GetFlowBrief handles POST /api/jobs/{id}/flow/brief
func (h *Handler) GetFlowBrief(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowBriefRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	if req.Filter == "" {
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	// Get cached text or generate new
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to get packets: %v", err))
			return
		}
		if result.ExitCode != 0 {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("tshark error: %s", strings.TrimSpace(result.Stderr)))
			return
		}

		compactJSON, err = packet.SimplifyPacketsJSON(result.Stdout)
		if err != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Parse and analyze the packets
	brief, err := analyzePacketsForBrief(compactJSON)
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to analyze packets: %v", err))
		return
	}

	writeSuccess(w, brief)
}

// analyzePacketsForBrief extracts summary info from compact JSON
func analyzePacketsForBrief(compactJSON string) (*FlowBriefResponse, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return nil, fmt.Errorf("failed to parse JSON: %w", err)
	}

	brief := &FlowBriefResponse{
		PacketCount:      len(packets),
		ProtocolsPresent: []string{},
		KeyParams:        &KeyParamsCandidates{},
	}

	protocolSet := make(map[string]bool)
	imsiSet := make(map[string]bool)
	supiSet := make(map[string]bool)
	ueipSet := make(map[string]bool)
	teidSet := make(map[string]bool)
	seidSet := make(map[string]bool)
	qfiSet := make(map[string]bool)
	ranIdSet := make(map[string]bool)
	amfIdSet := make(map[string]bool)

	var firstTime, lastTime string
	var firstRelative, lastRelative string

	for _, pkt := range packets {
		// Extract frame info
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if t, ok := frame["time_absolute"].(string); ok && t != "" {
				if firstTime == "" {
					firstTime = t
				}
				lastTime = t
			}
			if t, ok := frame["time"].(string); ok && t != "" {
				if firstRelative == "" {
					firstRelative = t
				}
				lastRelative = t
			}
		}

		// Extract application layer protocols and params
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for proto, info := range app {
				protocolSet[proto] = true
				if infoMap, ok := info.(map[string]interface{}); ok {
					extractKeyParams(proto, infoMap, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet)
				}
			}
		}

		// Also check layers for IPs that might be UE IPs
		if layers, ok := pkt["layers"].(map[string]interface{}); ok {
			// We'll collect src/dst IPs but filter later for UE candidates
			// For now, just note them
			_ = layers
		}
	}

	// Build protocol list
	for proto := range protocolSet {
		brief.ProtocolsPresent = append(brief.ProtocolsPresent, proto)
	}
	sort.Strings(brief.ProtocolsPresent)

	// Build key params
	brief.KeyParams.IMSI = setToSlice(imsiSet)
	brief.KeyParams.SUPI = setToSlice(supiSet)
	brief.KeyParams.UEIP = setToSlice(ueipSet)
	brief.KeyParams.TEID = setToSlice(teidSet)
	brief.KeyParams.SEID = setToSlice(seidSet)
	brief.KeyParams.QFI = setToSlice(qfiSet)
	brief.KeyParams.RanUeNgapID = setToSlice(ranIdSet)
	brief.KeyParams.AmfUeNgapID = setToSlice(amfIdSet)

	// Calculate time range
	if firstTime != "" && lastTime != "" {
		startSec, _ := parseEpochTime(firstTime)
		endSec, _ := parseEpochTime(lastTime)
		durationMs := (endSec - startSec) * 1000

		brief.TimeRange = &TimeRange{
			Start:         firstTime,
			End:           lastTime,
			DurationMs:    durationMs,
			StartRelative: firstRelative,
			EndRelative:   lastRelative,
		}
	}

	return brief, nil
}

// extractKeyParams extracts key parameters from protocol info
func extractKeyParams(proto string, info map[string]interface{}, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet map[string]bool) {
	// Helper to add string to set
	addToSet := func(set map[string]bool, key string) {
		if v, ok := info[key].(string); ok && v != "" {
			set[v] = true
		}
	}

	switch proto {
	case "ngap":
		// Look for NAS info nested in ngap
		if nas, ok := info["nas"].(map[string]interface{}); ok {
			if msin, ok := nas["msin"].(string); ok && msin != "" {
				// Reconstruct IMSI from mcc+mnc+msin if available
				mcc, _ := nas["mcc"].(string)
				mnc, _ := nas["mnc"].(string)
				if mcc != "" && mnc != "" {
					imsiSet[mcc+mnc+msin] = true
				} else {
					imsiSet[msin] = true
				}
			}
			if supi, ok := nas["supi"].(string); ok && supi != "" {
				supiSet[supi] = true
			}
		}
		// Look in ies for IDs
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractFromIEs(ies, ranIdSet, amfIdSet, ueipSet, teidSet, seidSet, qfiSet)
		}

	case "nas-5gs":
		addToSet(supiSet, "supi")
		if msin, ok := info["msin"].(string); ok && msin != "" {
			mcc, _ := info["mcc"].(string)
			mnc, _ := info["mnc"].(string)
			if mcc != "" && mnc != "" {
				imsiSet[mcc+mnc+msin] = true
			}
		}

	case "pfcp":
		addToSet(seidSet, "seid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractPFCPParams(ies, ueipSet, teidSet, qfiSet, seidSet)
		}

	case "gtpv2":
		addToSet(teidSet, "teid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractGTPv2Params(ies, imsiSet, teidSet, ueipSet)
		}

	case "gtp":
		addToSet(teidSet, "teid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractGTPUParams(ies, qfiSet)
		}

	case "s1ap":
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractS1APParams(ies, imsiSet, ueipSet)
		}
	}
}

// extractFromIEs recursively searches for key values in IE structures
func extractFromIEs(ies map[string]interface{}, ranIdSet, amfIdSet, ueipSet, teidSet, seidSet, qfiSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "ran-ue-ngap-id") || strings.Contains(keyLower, "ran_ue_ngap_id") {
					if s, ok := val.(string); ok && s != "" {
						ranIdSet[s] = true
					}
				}
				if strings.Contains(keyLower, "amf-ue-ngap-id") || strings.Contains(keyLower, "amf_ue_ngap_id") {
					if s, ok := val.(string); ok && s != "" {
						amfIdSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdu_address") || strings.Contains(keyLower, "ue_ip") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") || strings.Contains(keyLower, "f-teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "seid") || strings.Contains(keyLower, "f-seid") {
					if s, ok := val.(string); ok && s != "" {
						seidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractPFCPParams extracts PFCP-specific parameters
func extractPFCPParams(ies map[string]interface{}, ueipSet, teidSet, qfiSet, seidSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "ue_ip") || strings.Contains(keyLower, "pdu_address") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "seid") {
					if s, ok := val.(string); ok && s != "" {
						seidSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractGTPv2Params extracts GTPv2-specific parameters
func extractGTPv2Params(ies map[string]interface{}, imsiSet, teidSet, ueipSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "imsi") {
					if s, ok := val.(string); ok && s != "" {
						imsiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") || strings.Contains(keyLower, "f-teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdn_address") || strings.Contains(keyLower, "paa") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractGTPUParams extracts GTP-U specific parameters
func extractGTPUParams(ies map[string]interface{}, qfiSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractS1APParams extracts S1AP-specific parameters
func extractS1APParams(ies map[string]interface{}, imsiSet, ueipSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "imsi") {
					if s, ok := val.(string); ok && s != "" {
						imsiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdn_address") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// setToSlice converts a set to a sorted slice
func setToSlice(set map[string]bool) []string {
	if len(set) == 0 {
		return nil
	}
	result := make([]string, 0, len(set))
	for k := range set {
		result = append(result, k)
	}
	sort.Strings(result)
	return result
}

// parseEpochTime parses epoch time string to float64 seconds
func parseEpochTime(epochStr string) (float64, error) {
	// Format: "1703001234.123456789"
	return strconv.ParseFloat(epochStr, 64)
}

// isValidIP checks if a string looks like an IP address
func isValidIP(s string) bool {
	// Simple check: contains dots and only digits/dots (IPv4) or colons (IPv6)
	if strings.Contains(s, ".") {
		parts := strings.Split(s, ".")
		if len(parts) == 4 {
			for _, p := range parts {
				if _, err := strconv.Atoi(p); err != nil {
					return false
				}
			}
			return true
		}
	}
	if strings.Contains(s, ":") {
		// IPv6-like
		return true
	}
	return false
}

// GenerateFlow handles POST /api/jobs/{id}/flow/generate
func (h *Handler) GenerateFlow(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowGenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	if req.Filter == "" {
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	maxPackets := req.MaxEvents
	if maxPackets <= 0 {
		maxPackets = 1000 // default
	}

	// Get cached text or generate new (same data source as "复制JSON" button)
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to get packets: %v", err))
			return
		}
		if result.ExitCode != 0 {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("tshark error: %s", strings.TrimSpace(result.Stderr)))
			return
		}

		var err2 error
		compactJSON, err2 = packet.SimplifyPacketsJSON(result.Stdout)
		if err2 != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Limit the number of packets sent to LLM if needed
	limitedJSON, _, err := limitPacketsJSON(compactJSON, maxPackets)
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to process packets: %v", err))
		return
	}

	// Extract key params from compactJSON for response
	keyParams := extractKeyParamsFromJSON(compactJSON)

	// Extract packet columns using tshark (Protocol, Info, etc.)
	columnsCtx, columnsCancel := context.WithTimeout(context.Background(), 30*time.Second)
	packetColumns, err := tshark.TsharkPacketColumns(columnsCtx, job.MergedPcap, req.Filter)
	columnsCancel()
	if err != nil {
		log.Printf("[FlowGenerate] Warning: failed to extract packet columns: %v", err)
		packetColumns = nil // Continue without columns
	}

	// Filter heartbeat packets to make LLM input deterministic
	llmInputJSON, removedHeartbeats, err := filterHeartbeatPacketsJSON(limitedJSON)
	if err != nil {
		llmInputJSON = limitedJSON
		removedHeartbeats = 0
	}

	// Count packets in llmInputJSON and build valid frame numbers set
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(llmInputJSON), &packets); err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to parse packets: %v", err))
		return
	}
	packetCount := len(packets)

	// Build valid frame numbers set
	validFrameNumbers := make(map[string]bool)
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok && num != "" {
				validFrameNumbers[num] = true
			}
		}
	}

	log.Printf("[FlowGenerate] Job %s: %d packets after filtering (removed %d heartbeats)", id, packetCount, removedHeartbeats)

	// Use deterministic rule-based IP→NE inference (no LLM)
	annotations := InferIPMappingsWithEmptyStages(llmInputJSON)

	// No stage-based filtering - use all packets
	renderJSON := llmInputJSON
	flowName := "信令流程图"
	if annotations != nil && annotations.FlowName != "" {
		flowName = annotations.FlowName
	}

	// Generate Mermaid deterministically from Go using annotations and packet columns
	mermaid := buildDeterministicMermaid(renderJSON, flowName, annotations, packetColumns)

	// Build details mapping (guaranteed 1:1 with Mermaid)
	details := buildDetailsMapping(renderJSON)

	log.Printf("[FlowGenerate] Generated Mermaid with %d messages, annotations=%v", len(details), annotations != nil)

	writeSuccess(w, &FlowGenerateResponse{
		FlowName:      flowName,
		Mermaid:       mermaid,
		KeyParams:     keyParams,
		Details:       details,
		InputJSON:     renderJSON, // Return the subset JSON that matches the diagram
		Annotations:   annotations,
		PacketColumns: packetColumns,
	})
}

// limitPacketsJSON limits the number of packets in JSON array
func limitPacketsJSON(compactJSON string, maxPackets int) (string, int, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return "", 0, fmt.Errorf("failed to parse JSON: %w", err)
	}

	if len(packets) > maxPackets {
		packets = packets[:maxPackets]
	}

	result, err := json.Marshal(packets)
	if err != nil {
		return "", 0, fmt.Errorf("failed to marshal limited packets: %w", err)
	}

	return string(result), len(packets), nil
}

// extractKeyParamsFromJSON extracts key parameters from compactJSON
func extractKeyParamsFromJSON(compactJSON string) *KeyParamsCandidates {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return &KeyParamsCandidates{}
	}

	keyParams := &KeyParamsCandidates{}
	imsiSet := make(map[string]bool)
	supiSet := make(map[string]bool)
	ueipSet := make(map[string]bool)
	teidSet := make(map[string]bool)
	seidSet := make(map[string]bool)
	qfiSet := make(map[string]bool)
	ranIdSet := make(map[string]bool)
	amfIdSet := make(map[string]bool)

	for _, pkt := range packets {
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for proto, info := range app {
				if infoMap, ok := info.(map[string]interface{}); ok {
					extractKeyParams(proto, infoMap, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet)
				}
			}
		}
	}

	keyParams.IMSI = setToSlice(imsiSet)
	keyParams.SUPI = setToSlice(supiSet)
	keyParams.UEIP = setToSlice(ueipSet)
	keyParams.TEID = setToSlice(teidSet)
	keyParams.SEID = setToSlice(seidSet)
	keyParams.QFI = setToSlice(qfiSet)
	keyParams.RanUeNgapID = setToSlice(ranIdSet)
	keyParams.AmfUeNgapID = setToSlice(amfIdSet)

	return keyParams
}

// buildDetailsMapping builds the idx->originNumber mapping from input packets JSON.
// This is the fallback method when LLM doesn't provide a MAPPING section.
// It assumes sequential ordering: Mermaid autonumber idx corresponds to packet array index.
// idx and frame are both 1-based (matching Mermaid autonumber which starts at 1).
// originNumber is the pcap frame.number (Wireshark frame number).
func buildDetailsMapping(compactJSON string) []FlowMessageDetail {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return nil
	}

	details := make([]FlowMessageDetail, 0, len(packets))
	for i, pkt := range packets {
		detail := FlowMessageDetail{
			Idx:   i + 1, // 1-based index matching Mermaid autonumber
			Frame: i + 1, // 1-based position in input array
		}

		// Extract frame.number as originNumber
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok {
				detail.OriginNumber = num
			}
		}

		details = append(details, detail)
	}

	return details
}

// countHeartbeatMessages counts PFCP Heartbeat messages in the packet JSON.
func countHeartbeatMessages(compactJSON string) int {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return 0
	}

	count := 0
	for _, pkt := range packets {
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			if pfcp, ok := app["pfcp"].(map[string]interface{}); ok {
				// Check message field for Heartbeat
				if msg, ok := pfcp["message"].(string); ok {
					if strings.Contains(strings.ToLower(msg), "heartbeat") {
						count++
						continue
					}
				}
				// Check message_type field (1=Heartbeat Request, 2=Heartbeat Response)
				if msgType, ok := pfcp["message_type"].(string); ok {
					if msgType == "1" || msgType == "2" {
						count++
					}
				}
			}
		}
	}
	return count
}

// filterHeartbeatPacketsJSON removes PFCP heartbeat packets from the JSON array.
// This is important for absolute consistency: what we send to the LLM must be the same
// thing we later correlate in the web UI (and we don't want the model to decide "what is heartbeat").
func filterHeartbeatPacketsJSON(compactJSON string) (string, int, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return compactJSON, 0, err
	}

	isHeartbeat := func(pkt map[string]interface{}) bool {
		app, ok := pkt["application"].(map[string]interface{})
		if !ok {
			return false
		}
		pfcp, ok := app["pfcp"].(map[string]interface{})
		if !ok {
			return false
		}
		if msg, ok := pfcp["message"].(string); ok {
			if strings.Contains(strings.ToLower(msg), "heartbeat") {
				return true
			}
		}
		if msgType, ok := pfcp["message_type"].(string); ok {
			if msgType == "1" || msgType == "2" {
				return true
			}
		}
		return false
	}

	filtered := make([]map[string]interface{}, 0, len(packets))
	removed := 0
	for _, pkt := range packets {
		if isHeartbeat(pkt) {
			removed++
			continue
		}
		filtered = append(filtered, pkt)
	}

	out, err := json.Marshal(filtered)
	if err != nil {
		return compactJSON, 0, err
	}
	return string(out), removed, nil
}

// countMermaidMessages counts Mermaid sequenceDiagram message arrows in a best-effort way.
func countMermaidMessages(mermaid string) int {
	if strings.TrimSpace(mermaid) == "" {
		return 0
	}
	count := 0
	lines := strings.Split(mermaid, "\n")
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "%%") {
			continue
		}
		if strings.HasPrefix(line, "Note ") {
			continue
		}
		// A message line should contain ":" and an arrow.
		if !strings.Contains(line, ":") {
			continue
		}
		if strings.Contains(line, "->>") || strings.Contains(line, "-->>") || strings.Contains(line, "->") || strings.Contains(line, "-->") {
			count++
		}
	}
	return count
}


func safeOneLine(s string, max int) string {
	out := strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	out = strings.Join(strings.Fields(out), " ")
	if max > 0 && len(out) > max {
		return out[:max-3] + "..."
	}
	return out
}

func getString(m map[string]interface{}, key string) string {
	if v, ok := m[key]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

func inferRoleFromEndpoint(ip, port, proto string) string {
	if ip == "" {
		return "?"
	}
	if proto == "sctp" && port == "38412" {
		return "AMF"
	}
	if proto == "udp" && port == "8805" {
		return "SMF/UPF"
	}
	if proto == "udp" && port == "2123" {
		return "SGW/PGW"
	}
	return ip
}

func buildPacketTitle(pkt map[string]interface{}) string {
	frameNum := ""
	if frame, ok := pkt["frame"].(map[string]interface{}); ok {
		frameNum = getString(frame, "number")
	}

	app, _ := pkt["application"].(map[string]interface{})
	if app != nil {
		if ngap, ok := app["ngap"].(map[string]interface{}); ok {
			proc := getString(ngap, "procedure")
			if proc == "" {
				proc = getString(ngap, "procedureCode")
				if proc != "" {
					proc = "NGAP(" + proc + ")"
				}
			}
			if proc == "" {
				proc = "NGAP"
			}
			return safeOneLine("["+frameNum+"] "+proc, 80)
		}
		if nas, ok := app["nas-5gs"].(map[string]interface{}); ok {
			mm := getString(nas, "mm_message")
			sm := getString(nas, "sm_message")
			title := mm
			if title == "" {
				title = sm
			}
			if title == "" {
				title = "NAS-5GS"
			}
			return safeOneLine("["+frameNum+"] "+title, 80)
		}
		if pfcp, ok := app["pfcp"].(map[string]interface{}); ok {
			msg := getString(pfcp, "message")
			if msg == "" {
				msg = getString(pfcp, "message_type")
				if msg != "" {
					msg = "PFCP(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "PFCP"
			}
			return safeOneLine("["+frameNum+"] "+msg, 80)
		}
		if gtpv2, ok := app["gtpv2"].(map[string]interface{}); ok {
			msg := getString(gtpv2, "message")
			if msg == "" {
				msg = getString(gtpv2, "message_type")
				if msg != "" {
					msg = "GTPv2(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "GTPv2"
			}
			return safeOneLine("["+frameNum+"] "+msg, 80)
		}
		if s1ap, ok := app["s1ap"].(map[string]interface{}); ok {
			proc := getString(s1ap, "procedure")
			if proc == "" {
				proc = "S1AP"
			}
			return safeOneLine("["+frameNum+"] "+proc, 80)
		}
	}
	if frameNum != "" {
		return safeOneLine("Frame "+frameNum, 80)
	}
	return "Frame"
}

// buildPacketTitleNoFrame generates a message title without the [frameNum] prefix.
// Used for Mermaid diagrams since autonumber already provides sequence numbers.
func buildPacketTitleNoFrame(pkt map[string]interface{}) string {
	app, _ := pkt["application"].(map[string]interface{})
	if app != nil {
		if ngap, ok := app["ngap"].(map[string]interface{}); ok {
			proc := getString(ngap, "procedure")
			if proc == "" {
				proc = getString(ngap, "procedureCode")
				if proc != "" {
					proc = "NGAP(" + proc + ")"
				}
			}
			if proc == "" {
				proc = "NGAP"
			}
			return proc
		}
		if nas, ok := app["nas-5gs"].(map[string]interface{}); ok {
			mm := getString(nas, "mm_message")
			sm := getString(nas, "sm_message")
			title := mm
			if title == "" {
				title = sm
			}
			if title == "" {
				title = "NAS-5GS"
			}
			return title
		}
		if pfcp, ok := app["pfcp"].(map[string]interface{}); ok {
			msg := getString(pfcp, "message")
			if msg == "" {
				msg = getString(pfcp, "message_type")
				if msg != "" {
					msg = "PFCP(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "PFCP"
			}
			return msg
		}
		if gtpv2, ok := app["gtpv2"].(map[string]interface{}); ok {
			msg := getString(gtpv2, "message")
			if msg == "" {
				msg = getString(gtpv2, "message_type")
				if msg != "" {
					msg = "GTPv2(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "GTPv2"
			}
			return msg
		}
		if s1ap, ok := app["s1ap"].(map[string]interface{}); ok {
			proc := getString(s1ap, "procedure")
			if proc == "" {
				proc = "S1AP"
			}
			return proc
		}
	}
	
	// Fallback to Frame number
	if frame, ok := pkt["frame"].(map[string]interface{}); ok {
		if num := getString(frame, "number"); num != "" {
			return "Frame " + num
		}
	}
	return "Frame"
}

// isPFCPSessionMessage checks if the PFCP message type is a session-related message (50-57).
// These are: Session Establishment Request/Response, Session Modification Request/Response,
// Session Deletion Request/Response, Session Report Request/Response.
func isPFCPSessionMessage(msgType string) bool {
	switch msgType {
	case "50", "51", "52", "53", "54", "55", "56", "57":
		return true
	default:
		return false
	}
}

// extractPFCPSeidsFromPacket recursively extracts all SEIDs from a PFCP packet.
// Returns SEIDs from:
// 1. Header SEID (pfcp.seid) if non-empty and non-zero
// 2. F-SEID IEs: keys containing "F-SEID" with child keys containing "SEID"
func extractPFCPSeidsFromPacket(pfcpInfo map[string]interface{}) []string {
	seids := make(map[string]struct{})

	// 1. Get header SEID
	if headerSeid, ok := pfcpInfo["seid"].(string); ok && headerSeid != "" && headerSeid != "0" && headerSeid != "0x0" && headerSeid != "0x0000000000000000" {
		seids[headerSeid] = struct{}{}
	}

	// 2. Recursively search for F-SEID IEs
	var searchFSeid func(data interface{}, inFseid bool)
	searchFSeid = func(data interface{}, inFseid bool) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				// Check if we're entering an F-SEID structure
				isFseidKey := strings.Contains(keyLower, "f-seid") || strings.Contains(keyLower, "f_seid") || strings.Contains(keyLower, "fseid")
				// If we're inside an F-SEID and find a SEID value
				if inFseid && (strings.Contains(keyLower, "seid") && !strings.Contains(keyLower, "f-seid") && !strings.Contains(keyLower, "f_seid")) {
					if s, ok := val.(string); ok && s != "" && s != "0" && s != "0x0" && s != "0x0000000000000000" {
						seids[s] = struct{}{}
					}
				}
				// Recurse
				searchFSeid(val, inFseid || isFseidKey)
			}
		case []interface{}:
			for _, item := range v {
				searchFSeid(item, inFseid)
			}
		}
	}

	// Search in IEs
	if ies, ok := pfcpInfo["ies"].(map[string]interface{}); ok {
		searchFSeid(ies, false)
	}

	// Convert to slice
	result := make([]string, 0, len(seids))
	for seid := range seids {
		result = append(result, seid)
	}
	sort.Strings(result)
	return result
}

// extractPFCPDnnsFromPacket recursively extracts all DNN values from a PFCP packet.
// Returns DNNs from Network Instance IEs (case-insensitive key matching).
func extractPFCPDnnsFromPacket(pfcpInfo map[string]interface{}) []string {
	dnns := make(map[string]struct{})

	var searchDnn func(data interface{})
	searchDnn = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				// Match "network instance", "network_instance", "networkinstance"
				if strings.Contains(keyLower, "network") && strings.Contains(keyLower, "instance") {
					if s, ok := val.(string); ok && s != "" {
						// Clean up the DNN value (remove quotes, trim whitespace)
						dnn := strings.Trim(strings.TrimSpace(s), "\"'")
						if dnn != "" {
							dnns[dnn] = struct{}{}
						}
					}
				}
				// Recurse into nested structures
				searchDnn(val)
			}
		case []interface{}:
			for _, item := range v {
				searchDnn(item)
			}
		}
	}

	// Search in IEs
	if ies, ok := pfcpInfo["ies"].(map[string]interface{}); ok {
		searchDnn(ies)
	}

	// Convert to slice and sort for deterministic output
	result := make([]string, 0, len(dnns))
	for dnn := range dnns {
		result = append(result, dnn)
	}
	sort.Strings(result)
	return result
}

// buildDeterministicMermaid builds a guaranteed-consistent sequence diagram from the exact input JSON.
// It creates exactly one Mermaid message per packet in the same order, so message count == mapping count == input packets.
// If annotations are provided, uses ip_map for participant naming and inserts stage notes.
//
// NEW DESIGN (IP-keyed nodes):
// - Participants are keyed by unique IP address (not by "Role(IP)" string matching)
// - Message direction strictly follows packet's src_ip → dst_ip
// - ip_map from annotations provides display names; unknown IPs show raw IP
// - No port-based role inference for naming (avoids ambiguity)
//
// DNN LABELING:
// - For PFCP session messages (msg_type 50-57), appends （dnn1,dnn2） suffix to message title
// - DNNs are extracted from Network Instance IEs and propagated via SEID mapping
func buildDeterministicMermaid(compactJSON string, flowName string, ann *FlowAnnotationsV1, packetColumns map[string]*tshark.PacketColumns) string {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return "sequenceDiagram\n    autonumber\n"
	}

	// Build IP→NE lookup from annotations
	ipToNE := make(map[string]string)
	if ann != nil {
		for _, m := range ann.IPMap {
			if m.IP != "" && m.NE != "" {
				ipToNE[m.IP] = m.NE
			}
		}
	}

	// Build frame→stage lookup from annotations
	// frameToStage: first frame of each stage → stage (for inserting stage notes)
	// NOTE: We no longer use per-frame title/note from annotations - we use tshark columns instead
	frameToStage := make(map[string]*FlowStage)
	if ann != nil {
		for i := range ann.Stages {
			s := &ann.Stages[i]
			if len(s.Frames) > 0 {
				// First frame of stage triggers the stage note
				frameToStage[s.Frames[0].Number] = s
			}
		}
	}

	// Use flow_name from annotations if available
	if ann != nil && ann.FlowName != "" {
		flowName = ann.FlowName
	}

	// ========== NEW: IP-keyed participant collection ==========
	// ipNode holds info for a unique IP participant
	type ipNode struct {
		IP         string // unique key
		Role       string // from ipToNE, or "Unknown"
		FirstSeen  int    // order of first appearance (0-based)
		GroupIndex int    // index in roleOrder for sorting
	}

	// Collect unique IPs in first-seen order
	ipNodes := make(map[string]*ipNode) // key = IP
	ipOrder := make([]string, 0, 8)     // IPs in first-seen order
	seenCount := 0

	ensureIP := func(ip string) {
		if ip == "" {
			ip = "?"
		}
		if _, exists := ipNodes[ip]; exists {
			return
		}
		// Get role from annotations, default to "Unknown"
		role := "Unknown"
		if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
			role = ne
		}
		ipNodes[ip] = &ipNode{
			IP:         ip,
			Role:       role,
			FirstSeen:  seenCount,
			GroupIndex: getRoleGroupIndex(role),
		}
		ipOrder = append(ipOrder, ip)
		seenCount++
	}

	// Message structure: store IPs directly, not derived names
	type Msg struct {
		FromIP      string
		ToIP        string
		Title       string
		FrameNumber string // frame.number for looking up stage/frame info
	}
	msgs := make([]Msg, 0, len(packets))

	// PFCP SEID → DNNs mapping for DNN label propagation across session messages
	// Key: SEID string, Value: set of DNN strings
	seidToDnns := make(map[string]map[string]struct{})

	for _, pkt := range packets {
		layers, _ := pkt["layers"].(map[string]interface{})
		srcIP := ""
		dstIP := ""
		if layers != nil {
			srcIP = getString(layers, "src_ip")
			dstIP = getString(layers, "dst_ip")
		}
		if srcIP == "" {
			srcIP = "?"
		}
		if dstIP == "" {
			dstIP = "?"
		}

		// Get frame.number
		frameNum := ""
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			frameNum = getString(frame, "number")
		}

		// Register IPs as participants (in first-seen order)
		ensureIP(srcIP)
		ensureIP(dstIP)

		// Determine title: prefer tshark column info (Protocol + InfoClean)
		// This gives us the exact same output as Wireshark's packet list
		// NOTE: We don't add [frameNum] prefix because Mermaid's autonumber already shows sequence numbers
		var title string
		if cols, ok := packetColumns[frameNum]; ok && cols.InfoClean != "" {
			// Use tshark-extracted Protocol + cleaned Info (SACK prefix removed)
			title = fmt.Sprintf("%s %s", cols.Protocol, cols.InfoClean)
		} else {
			// Fallback: use legacy buildPacketTitle when tshark columns not available
			title = buildPacketTitleNoFrame(pkt)
		}

		// PFCP DNN labeling: extract SEIDs and DNNs, update mapping, and decorate title
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			if pfcpInfo, ok := app["pfcp"].(map[string]interface{}); ok {
				msgType := getString(pfcpInfo, "message_type")

				// Extract SEIDs and DNNs from this packet
				seidsInPkt := extractPFCPSeidsFromPacket(pfcpInfo)
				dnnsInPkt := extractPFCPDnnsFromPacket(pfcpInfo)

				// Build union of DNNs: dnnsInPkt + existing mappings for seidsInPkt
				unionDnns := make(map[string]struct{})
				for _, dnn := range dnnsInPkt {
					unionDnns[dnn] = struct{}{}
				}
				for _, seid := range seidsInPkt {
					if existingDnns, ok := seidToDnns[seid]; ok {
						for dnn := range existingDnns {
							unionDnns[dnn] = struct{}{}
						}
					}
				}

				// Propagate: update seidToDnns for all SEIDs in this packet
				if len(unionDnns) > 0 {
					for _, seid := range seidsInPkt {
						if seidToDnns[seid] == nil {
							seidToDnns[seid] = make(map[string]struct{})
						}
						for dnn := range unionDnns {
							seidToDnns[seid][dnn] = struct{}{}
						}
					}
				}

				// Decorate title for PFCP session messages (msg_type 50-57)
				if isPFCPSessionMessage(msgType) && len(unionDnns) > 0 {
					// Convert to sorted slice for deterministic output
					dnnList := make([]string, 0, len(unionDnns))
					for dnn := range unionDnns {
						dnnList = append(dnnList, dnn)
					}
					sort.Strings(dnnList)
					// Append DNN suffix with full-width parentheses
					title = title + "（" + strings.Join(dnnList, ",") + "）"
				}
			}
		}

		msgs = append(msgs, Msg{FromIP: srcIP, ToIP: dstIP, Title: title, FrameNumber: frameNum})
	}

	// ========== Sort IPs by role order, then first-seen within same role ==========
	sortedIPs := make([]string, len(ipOrder))
	copy(sortedIPs, ipOrder)
	sort.SliceStable(sortedIPs, func(i, j int) bool {
		ni, nj := ipNodes[sortedIPs[i]], ipNodes[sortedIPs[j]]
		if ni.GroupIndex != nj.GroupIndex {
			return ni.GroupIndex < nj.GroupIndex
		}
		return ni.FirstSeen < nj.FirstSeen
	})

	// ========== Generate display names with numbering for duplicate roles ==========
	// Count how many IPs per role
	roleCounts := make(map[string]int)
	for _, ip := range sortedIPs {
		roleCounts[ipNodes[ip].Role]++
	}

	// Build display name and ID for each IP
	idByIP := make(map[string]string, len(sortedIPs))      // IP → "P1", "P2", ...
	displayByIP := make(map[string]string, len(sortedIPs)) // IP → "AMF(10.x)" or "10.x"
	roleSeq := make(map[string]int)                        // current sequence number for each role

	for i, ip := range sortedIPs {
		node := ipNodes[ip]
		idByIP[ip] = fmt.Sprintf("P%d", i+1)

		if node.Role == "Unknown" || node.Role == "?" {
			// Unknown role: just show IP
			displayByIP[ip] = ip
		} else if roleCounts[node.Role] > 1 {
			// Multiple IPs with same role: add number
			roleSeq[node.Role]++
			displayByIP[ip] = fmt.Sprintf("%s%d(%s)", node.Role, roleSeq[node.Role], ip)
		} else {
			// Single IP for this role
			displayByIP[ip] = fmt.Sprintf("%s(%s)", node.Role, ip)
		}
	}

	// ========== Build Mermaid output ==========
	var b strings.Builder
	b.WriteString("sequenceDiagram\n")
	b.WriteString("    autonumber\n")
	if strings.TrimSpace(flowName) != "" {
		b.WriteString("    %% ")
		b.WriteString(safeOneLine(flowName, 120))
		b.WriteString("\n")
	}
	for _, ip := range sortedIPs {
		b.WriteString("    participant ")
		b.WriteString(idByIP[ip])
		b.WriteString(" as ")
		b.WriteString(safeOneLine(displayByIP[ip], 60))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	// Get first and last participant IDs for Note over
	firstPID := "P1"
	lastPID := fmt.Sprintf("P%d", len(sortedIPs))
	if len(sortedIPs) == 0 {
		lastPID = "P1"
	}

	for _, m := range msgs {
		// Insert stage note if this frame is the first of a stage
		if stage, ok := frameToStage[m.FrameNumber]; ok {
			b.WriteString("\n    Note over ")
			b.WriteString(firstPID)
			b.WriteString(",")
			b.WriteString(lastPID)
			b.WriteString(": === ")
			b.WriteString(safeOneLine(stage.Name, 40))
			if stage.Summary != "" {
				b.WriteString(" === ")
				b.WriteString(safeOneLine(stage.Summary, 60))
			}
			b.WriteString("\n\n")
		}

		// Use IP directly to get participant ID (no string matching needed)
		fromID := idByIP[m.FromIP]
		toID := idByIP[m.ToIP]
		if fromID == "" {
			fromID = "P1"
		}
		if toID == "" {
			toID = "P1"
		}
		b.WriteString("    ")
		b.WriteString(fromID)
		b.WriteString("->>")
		b.WriteString(toID)
		b.WriteString(": ")
		// Increase max length to show complete message (0 = no limit)
		b.WriteString(safeOneLine(m.Title, 0))
		b.WriteString("\n")
		// NOTE: Per-frame notes are no longer rendered.
		// Message details are shown via tshark columns in the frontend details panel.
	}
	return b.String()
}

// getRoleForIP returns the network element role for an IP from annotations.
// Returns "Unknown" if IP is not found in the annotation map.
// This is used for IP-keyed participant identification.
func getRoleForIP(ip string, ipToNE map[string]string) string {
	if ip == "" {
		return "Unknown"
	}
	if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
		return ne
	}
	return "Unknown"
}

// getDisplayNameForIP returns the display name for an IP participant.
// If role is known from annotations: "Role(IP)" or "Role{n}(IP)" for multiple same-role IPs.
// If role is unknown: just "IP".
// Parameters:
// - ip: the IP address
// - role: the role from annotations (or "Unknown")
// - seq: sequence number for this role (1-based, 0 means don't add number)
// - needsNumber: whether to add sequence number (true if multiple IPs have same role)
func getDisplayNameForIP(ip, role string, seq int, needsNumber bool) string {
	if ip == "" {
		return "?"
	}
	if role == "Unknown" || role == "" {
		return ip
	}
	if needsNumber && seq > 0 {
		return fmt.Sprintf("%s%d(%s)", role, seq, ip)
	}
	return fmt.Sprintf("%s(%s)", role, ip)
}

// inferRoleWithAnnotations infers the network element role from IP, using annotations if available.
// DEPRECATED: This function is kept for backward compatibility.
// New code should use getRoleForIP and getDisplayNameForIP instead.
// No longer falls back to port-based inference (per IP-keyed design).
func inferRoleWithAnnotations(ip, port, proto string, ipToNE map[string]string) string {
	if ip == "" {
		return "?"
	}

	// Check annotations - return display name if found
	if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
		return fmt.Sprintf("%s(%s)", ne, ip)
	}

	// No port-based fallback: just return raw IP for unknown
	return ip
}



// deduplicateIPMap removes duplicate IP entries, keeping the last (or highest confidence) one.
func deduplicateIPMap(ipMap []IPMapping) []IPMapping {
	if len(ipMap) == 0 {
		return ipMap
	}

	seen := make(map[string]int) // ip -> index in result
	result := make([]IPMapping, 0, len(ipMap))

	for _, m := range ipMap {
		ip := strings.TrimSpace(m.IP)
		if ip == "" {
			continue
		}
		m.IP = ip
		m.NE = normalizeNEType(m.NE)

		if existingIdx, ok := seen[ip]; ok {
			// Keep the one with higher confidence, or the new one if confidence is equal/higher
			if m.Confidence >= result[existingIdx].Confidence {
				result[existingIdx] = m
			}
		} else {
			seen[ip] = len(result)
			result = append(result, m)
		}
	}

	return result
}

// normalizeNEType normalizes network element type names.
func normalizeNEType(ne string) string {
	ne = strings.TrimSpace(ne)
	upper := strings.ToUpper(ne)

	// Normalize common variations
	switch upper {
	case "GNB", "ENB", "GNODEB", "ENODEB":
		if strings.HasPrefix(upper, "E") {
			return "eNB"
		}
		return "gNB"
	case "AMF", "MME", "SMF", "UPF", "SGW", "PGW", "HSS", "UDM", "AUSF", "PCRF":
		return upper
	case "S-GW", "SGW-C", "SGW-U":
		return "SGW"
	case "P-GW", "PGW-C", "PGW-U":
		return "PGW"
	case "UNKNOWN", "":
		return "Unknown"
	default:
		return ne // Keep original if not recognized
	}
}


// truncateForLog truncates a string for logging purposes.
func truncateForLog(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// participantInfo holds parsed info about a participant for sorting
type participantInfo struct {
	FullName   string // e.g., "AMF(10.18.11.20)"
	Role       string // e.g., "AMF"
	IP         string // e.g., "10.18.11.20"
	FirstSeen  int    // order of first appearance
	GroupIndex int    // index in roleOrder for sorting
}

// roleOrder defines the fixed ordering of network element roles.
// gNB* → AMF* → SMF* → UPF* → other NEs
var roleOrder = []string{"gNB", "eNB", "AMF", "MME", "SMF", "PGW", "UPF", "SGW"}

// getRoleGroupIndex returns the index in roleOrder for a given role, or a large number for unknown roles.
func getRoleGroupIndex(role string) int {
	for i, r := range roleOrder {
		if strings.EqualFold(role, r) {
			return i
		}
	}
	return len(roleOrder) // Unknown roles go at the end
}

// parseParticipantName extracts role and IP from a participant name like "AMF(10.18.11.20)"
func parseParticipantName(name string) (role, ip string) {
	if idx := strings.Index(name, "("); idx != -1 {
		role = name[:idx]
		if endIdx := strings.Index(name, ")"); endIdx > idx {
			ip = name[idx+1 : endIdx]
		}
	} else {
		role = name
	}
	return
}

// sortAndNumberParticipants sorts participants by role group order and numbers duplicates.
// Order: gNB* → AMF* → SMF* → UPF* → others
// Same role with multiple IPs get numbered: gNB1(10.x), gNB2(10.y)
func sortAndNumberParticipants(participants []string) []string {
	if len(participants) == 0 {
		return participants
	}

	// Parse all participants
	infos := make([]participantInfo, len(participants))
	for i, p := range participants {
		role, ip := parseParticipantName(p)
		infos[i] = participantInfo{
			FullName:   p,
			Role:       role,
			IP:         ip,
			FirstSeen:  i,
			GroupIndex: getRoleGroupIndex(role),
		}
	}

	// Sort by group index, then by first seen order within group
	sort.SliceStable(infos, func(i, j int) bool {
		if infos[i].GroupIndex != infos[j].GroupIndex {
			return infos[i].GroupIndex < infos[j].GroupIndex
		}
		return infos[i].FirstSeen < infos[j].FirstSeen
	})

	// Number duplicates within same role
	roleCounts := make(map[string]int)
	for _, info := range infos {
		roleCounts[info.Role]++
	}

	result := make([]string, len(infos))
	roleSeq := make(map[string]int) // current sequence number for each role

	for i, info := range infos {
		if roleCounts[info.Role] > 1 {
			// Multiple instances of this role - add number
			roleSeq[info.Role]++
			seq := roleSeq[info.Role]
			if info.IP != "" {
				result[i] = fmt.Sprintf("%s%d(%s)", info.Role, seq, info.IP)
			} else {
				result[i] = fmt.Sprintf("%s%d", info.Role, seq)
			}
		} else {
			// Single instance - keep original name
			result[i] = info.FullName
		}
	}

	return result
}


// GenerateFlowStream handles POST /api/jobs/{id}/flow/generate/stream
// Uses Server-Sent Events to stream the flow generation progress.
// IP→NE mappings are inferred deterministically from protocol rules;
// Mermaid diagram is always generated deterministically by Go.
func (h *Handler) GenerateFlowStream(w http.ResponseWriter, r *http.Request) {
	startTime := time.Now()
	id := r.PathValue("id")

	log.Printf("[FlowGenerateStream] ========== STREAM FLOW GENERATION START ==========")
	log.Printf("[FlowGenerateStream] Job ID: %s", id)

	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		log.Printf("[FlowGenerateStream] ERROR: Job not found: %s", id)
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowGenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Printf("[FlowGenerateStream] ERROR: Invalid request body: %v", err)
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	log.Printf("[FlowGenerateStream] Request: filter=%q, max_events=%d", req.Filter, req.MaxEvents)

	if req.Filter == "" {
		log.Printf("[FlowGenerateStream] ERROR: Filter is required")
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	maxPackets := req.MaxEvents
	if maxPackets <= 0 {
		maxPackets = 200
	}
	log.Printf("[FlowGenerateStream] Using maxPackets=%d", maxPackets)

	// Set up SSE headers
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	flusher, ok := w.(http.Flusher)
	if !ok {
		writeError(w, http.StatusInternalServerError, "streaming not supported")
		return
	}

	// Helper to send SSE event
	sendEvent := func(event, data string) {
		fmt.Fprintf(w, "event: %s\ndata: %s\n\n", event, data)
		flusher.Flush()
	}

	// Get cached text or generate new (same data source as "复制JSON" button)
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			sendEvent("error", fmt.Sprintf(`{"message":"failed to get packets: %s"}`, err.Error()))
			return
		}
		if result.ExitCode != 0 {
			sendEvent("error", fmt.Sprintf(`{"message":"tshark error: %s"}`, strings.TrimSpace(result.Stderr)))
			return
		}

		var err2 error
		compactJSON, err2 = packet.SimplifyPacketsJSON(result.Stdout)
		if err2 != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Limit the number of packets sent to LLM if needed
	limitedJSON, _, err := limitPacketsJSON(compactJSON, maxPackets)
	if err != nil {
		sendEvent("error", fmt.Sprintf(`{"message":"failed to process packets: %s"}`, err.Error()))
		return
	}

	// Extract key params from compactJSON
	keyParams := extractKeyParamsFromJSON(compactJSON)

	// Extract packet columns using tshark (Protocol, Info, etc.)
	// These are used for Mermaid labels and frontend details panel.
	log.Printf("[FlowGenerateStream] Extracting packet columns via tshark...")
	columnsCtx, columnsCancel := context.WithTimeout(context.Background(), 30*time.Second)
	packetColumns, err := tshark.TsharkPacketColumns(columnsCtx, job.MergedPcap, req.Filter)
	columnsCancel()
	if err != nil {
		log.Printf("[FlowGenerateStream] Warning: failed to extract packet columns: %v", err)
		packetColumns = nil // Continue without columns
	} else {
		log.Printf("[FlowGenerateStream] Extracted packet columns for %d frames", len(packetColumns))
	}

	// Filter heartbeat packets so LLM input is deterministic and correlation is absolute.
	llmInputJSON, removedHeartbeats, err := filterHeartbeatPacketsJSON(limitedJSON)
	if err != nil {
		llmInputJSON = limitedJSON
		removedHeartbeats = 0
	}

	// Count packets in llmInputJSON and build valid frame numbers set
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(llmInputJSON), &packets); err != nil {
		sendEvent("error", fmt.Sprintf(`{"message":"failed to parse packets: %s"}`, err.Error()))
		return
	}
	packetCount := len(packets)

	// Build valid frame numbers set
	validFrameNumbers := make(map[string]bool)
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok && num != "" {
				validFrameNumbers[num] = true
			}
		}
	}

	log.Printf("[FlowGenerateStream] Packet processing: total=%d, removed_heartbeats=%d, final=%d",
		packetCount+removedHeartbeats, removedHeartbeats, packetCount)

	// Log input packets summary
	log.Printf("[FlowGenerateStream] Input packets summary (%d packets):", packetCount)
	previewCount := packetCount
	if previewCount > 8 {
		previewCount = 8
	}
	for i := 0; i < previewCount; i++ {
		pkt := packets[i]
		frameNum := ""
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			frameNum = getString(frame, "number")
		}
		proto := ""
		msgType := ""
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for protoName, protoData := range app {
				proto = protoName
				if pd, ok := protoData.(map[string]interface{}); ok {
					if procedure, ok := pd["procedure"].(string); ok {
						msgType = procedure
					} else if message, ok := pd["message"].(string); ok {
						msgType = message
					} else if mmMsg, ok := pd["mm_message"].(string); ok {
						msgType = mmMsg
					}
				}
				break
			}
		}
		log.Printf("[FlowGenerateStream]   [%d] frame=%s, proto=%s, msg=%s",
			i+1, frameNum, proto, safeOneLine(msgType, 50))
	}
	if packetCount > 8 {
		log.Printf("[FlowGenerateStream]   ... (%d more packets)", packetCount-8)
	}

	// Send key params first
	if keyParams != nil {
		keyParamsJSON, _ := json.Marshal(keyParams)
		sendEvent("key_params", string(keyParamsJSON))
		log.Printf("[FlowGenerateStream] Sent key_params event")
	}

	// Send input_json for frontend to derive rich details from original packets
	inputJSONEscaped, err := json.Marshal(llmInputJSON)
	if err != nil {
		log.Printf("[FlowGenerateStream] ERROR: Failed to marshal input_json: %v", err)
	} else {
		escapedStr := string(inputJSONEscaped)
		log.Printf("[FlowGenerateStream] Sending input_json: size=%d bytes", len(escapedStr))
		sendEvent("input_json", escapedStr)
	}

	// Build and send details_map (idx->originNumber mapping) for frontend correlation
	// This is always sequential (1:1 with packets) since Go generates Mermaid deterministically
	detailsMap := buildDetailsMapping(llmInputJSON)
	detailsMapJSON, _ := json.Marshal(detailsMap)
	sendEvent("details_map", string(detailsMapJSON))
	log.Printf("[FlowGenerateStream] Sent details_map: %d entries", len(detailsMap))

	// Use deterministic rule-based IP→NE inference (no LLM)
	log.Printf("[FlowGenerateStream] Using deterministic IP→NE inference (no LLM)")
	annotations := InferIPMappingsWithEmptyStages(llmInputJSON)

	// No stage-based filtering - use all packets
	renderJSON := llmInputJSON
	flowName := "信令流程图"
	if annotations != nil && annotations.FlowName != "" {
		flowName = annotations.FlowName
	}

	// Log inferred annotations
	if annotations != nil {
		log.Printf("[FlowGenerateStream] Inferred annotations: ip_map=%d entries", len(annotations.IPMap))
		for i, m := range annotations.IPMap {
			log.Printf("[FlowGenerateStream]   IPMap[%d]: %s -> %s (conf=%.2f)", i, m.IP, m.NE, m.Confidence)
		}
	}

	// Generate Mermaid deterministically from Go using annotations and packet columns
	log.Printf("[FlowGenerateStream] Generating deterministic Mermaid diagram...")
	mermaid := buildDeterministicMermaid(renderJSON, flowName, annotations, packetColumns)
	log.Printf("[FlowGenerateStream] Generated Mermaid: length=%d bytes", len(mermaid))

	// Log Mermaid preview
	mermaidLines := strings.Split(mermaid, "\n")
	previewLineCount := len(mermaidLines)
	if previewLineCount > 10 {
		previewLineCount = 10
	}
	log.Printf("[FlowGenerateStream] Mermaid preview (first %d lines):", previewLineCount)
	for i := 0; i < previewLineCount; i++ {
		log.Printf("[FlowGenerateStream]   [%d] %s", i+1, safeOneLine(mermaidLines[i], 80))
	}
	if len(mermaidLines) > 10 {
		log.Printf("[FlowGenerateStream]   ... (%d more lines)", len(mermaidLines)-10)
	}

	// Build details mapping from the render JSON (guaranteed 1:1 with Mermaid)
	finalDetailsMap := buildDetailsMapping(renderJSON)
	log.Printf("[FlowGenerateStream] Built final details mapping: %d entries", len(finalDetailsMap))

	// Build stats
	stats := FlowValidationStats{
		InputPackets:      packetCount,
		MermaidMessages:   len(finalDetailsMap),
		MappingEntries:    len(finalDetailsMap),
		RemovedHeartbeats: removedHeartbeats,
	}
	log.Printf("[FlowGenerateStream] Stats: input=%d, mermaid_msgs=%d, mapping=%d, removed_heartbeats=%d",
		stats.InputPackets, stats.MermaidMessages, stats.MappingEntries, stats.RemovedHeartbeats)

	finalEvent := FlowFinalEvent{
		FlowName:      flowName,
		Mermaid:       mermaid,
		Details:       finalDetailsMap,
		Mode:          "go_deterministic",
		Stats:         &stats,
		Annotations:   annotations,
		PacketColumns: packetColumns,
	}
	finalJSON, _ := json.Marshal(finalEvent)
	sendEvent("flow_final", string(finalJSON))
	log.Printf("[FlowGenerateStream] Sent flow_final event: %d bytes", len(finalJSON))

	// Also send the updated input_json that matches the diagram
	updatedInputJSON, _ := json.Marshal(renderJSON)
	sendEvent("input_json_final", string(updatedInputJSON))
	log.Printf("[FlowGenerateStream] Sent input_json_final event: %d bytes", len(updatedInputJSON))

	// Send done event after flow_final so frontend can render validated content.
	sendEvent("done", `{"status":"completed"}`)

	elapsed := time.Since(startTime)
	log.Printf("[FlowGenerateStream] ========== STREAM FLOW GENERATION END (success) ==========")
	log.Printf("[FlowGenerateStream] Completed in %v: flow_name=%q, annotations=%v, mermaid_messages=%d",
		elapsed, flowName, annotations != nil, len(finalDetailsMap))

	// Async prefetch protocol trees for all frames in the flow (improves UX when clicking messages)
	go h.prefetchProtocolTrees(id, req.Filter, finalDetailsMap, packetColumns, job.MergedPcap)
}

// prefetchFilterHash generates a hash for the filter to track prefetch status
func prefetchFilterHash(filter string) string {
	h := sha256.Sum256([]byte(filter))
	return hex.EncodeToString(h[:8]) // 16 hex chars is enough for dedup
}

// prefetchProtocolTrees asynchronously prefetches protocol trees for all frames in a flow.
// This runs in the background after GenerateFlowStream completes, populating job.TreeCache
// so that subsequent GET /packets/{frame}/tree requests can hit the cache.
func (h *Handler) prefetchProtocolTrees(
	jobID string,
	filter string,
	detailsMap []FlowMessageDetail,
	packetColumns map[string]*tshark.PacketColumns,
	pcapPath string,
) {
	filterHash := prefetchFilterHash(filter)

	// Check if already prefetched (returns true if already marked)
	if h.jobMgr.MarkTreePrefetched(jobID, filterHash) {
		log.Printf("[TreePrefetch] Already prefetched for job=%s filter_hash=%s, skipping", jobID, filterHash)
		return
	}

	log.Printf("[TreePrefetch] Starting prefetch for job=%s filter_hash=%s, %d frames",
		jobID, filterHash, len(detailsMap))
	startTime := time.Now()

	// Group frames by protocol
	protoFrames := make(map[string][]int) // proto -> list of frame numbers
	for _, detail := range detailsMap {
		if detail.OriginNumber == "" {
			continue
		}
		frameNum := 0
		if _, err := fmt.Sscanf(detail.OriginNumber, "%d", &frameNum); err != nil || frameNum <= 0 {
			continue
		}

		// Get protocol from packetColumns
		cols, ok := packetColumns[detail.OriginNumber]
		if !ok || cols.Protocol == "" {
			continue
		}

		// Map display protocol to tshark filter protocol
		proto := tshark.MapDisplayProtocolToTsharkFilter(cols.Protocol)
		if !tshark.IsAllowedProtocol(proto) {
			continue
		}

		protoFrames[proto] = append(protoFrames[proto], frameNum)
	}

	if len(protoFrames) == 0 {
		log.Printf("[TreePrefetch] No valid frames to prefetch")
		return
	}

	// Log grouped frames
	for proto, frames := range protoFrames {
		log.Printf("[TreePrefetch] Protocol %q: %d frames", proto, len(frames))
	}

	// Run batch extraction per protocol with limited concurrency
	const maxConcurrency = 3
	var wg sync.WaitGroup
	semaphore := make(chan struct{}, maxConcurrency)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	totalCached := 0
	var cacheMu sync.Mutex

	for proto, frames := range protoFrames {
		wg.Add(1)
		go func(proto string, frames []int) {
			defer wg.Done()
			semaphore <- struct{}{}        // Acquire
			defer func() { <-semaphore }() // Release

			protoStart := time.Now()
			trees, err := tshark.TsharkProtocolTreeBatch(ctx, pcapPath, frames, proto)
			if err != nil {
				log.Printf("[TreePrefetch] Error extracting %q trees: %v", proto, err)
				return
			}

			// Cache all extracted trees
			cached := 0
			for frameNum, tree := range trees {
				if tree == "" {
					continue
				}
				cacheKey := job.TreeCacheKey(proto, frameNum)
				h.jobMgr.CacheProtocolTree(jobID, cacheKey, tree)
				cached++
			}

			cacheMu.Lock()
			totalCached += cached
			cacheMu.Unlock()

			log.Printf("[TreePrefetch] Protocol %q: cached %d/%d trees in %v",
				proto, cached, len(frames), time.Since(protoStart))
		}(proto, frames)
	}

	wg.Wait()
	log.Printf("[TreePrefetch] Completed for job=%s: cached %d trees in %v",
		jobID, totalCached, time.Since(startTime))
}
