package api

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"uepcap/internal/packet"
	"uepcap/internal/tshark"
)

// FlowBriefRequest represents the request for flow brief
type FlowBriefRequest struct {
	Filter string `json:"filter"`
}

// FlowBriefResponse represents the brief summary of filtered packets
type FlowBriefResponse struct {
	PacketCount      int                  `json:"packet_count"`
	TimeRange        *TimeRange           `json:"time_range,omitempty"`
	ProtocolsPresent []string             `json:"protocols_present"`
	KeyParams        *KeyParamsCandidates `json:"key_params"`
}

// TimeRange represents the time span of packets
type TimeRange struct {
	Start         string  `json:"start"`          // absolute time
	End           string  `json:"end"`            // absolute time
	DurationMs    float64 `json:"duration_ms"`    // duration in milliseconds
	StartRelative string  `json:"start_relative"` // relative time
	EndRelative   string  `json:"end_relative"`   // relative time
}

// KeyParamsCandidates holds key parameters extracted from packets
type KeyParamsCandidates struct {
	IMSI        []string `json:"imsi,omitempty"`
	SUPI        []string `json:"supi,omitempty"`
	UEIP        []string `json:"ue_ip,omitempty"`
	TEID        []string `json:"teid,omitempty"`
	SEID        []string `json:"seid,omitempty"`
	QFI         []string `json:"qfi,omitempty"`
	RanUeNgapID []string `json:"ran_ue_ngap_id,omitempty"`
	AmfUeNgapID []string `json:"amf_ue_ngap_id,omitempty"`
}

// FlowGenerateRequest represents the request for flow generation
type FlowGenerateRequest struct {
	Filter    string `json:"filter"`
	MaxEvents int    `json:"max_events,omitempty"` // max events to send to LLM (default 200)
}

// FlowGenerateResponse represents the response with Mermaid diagram
type FlowGenerateResponse struct {
	FlowName  string               `json:"flow_name"`
	Mermaid   string               `json:"mermaid"`
	KeyParams *KeyParamsCandidates `json:"key_params,omitempty"`
	// Details is the mapping from Mermaid autonumber index to original packet frame.number.
	// Frontend uses this to correlate diagram messages with input packets.
	Details []FlowMessageDetail `json:"details,omitempty"`
	// InputJSON is the original compact packet JSON sent to LLM (for frontend to derive rich details).
	InputJSON string `json:"input_json,omitempty"`
	// Annotations contains LLM-provided IP→NE mapping and stage segmentation.
	// May be nil if LLM parsing failed (diagram still generated deterministically by Go).
	Annotations *FlowAnnotationsV1 `json:"annotations,omitempty"`
}

// FlowMessageDetail maps a Mermaid message (by autonumber index) to the original packet.
// idx: 1-based message order in the Mermaid diagram (matches autonumber order).
// frame: 1-based input packet index (position in the input JSON array).
// originNumber: the original capture frame.number from pcap (Wireshark frame number).
type FlowMessageDetail struct {
	Idx          int    `json:"idx"`
	Frame        int    `json:"frame,omitempty"`
	OriginNumber string `json:"originNumber,omitempty"` // original pcap frame.number
}

// FlowFinalEvent is sent to the frontend via SSE after the LLM stream completes.
// It guarantees that the Mermaid and details_map are consistent with the exact input_json
// that was sent to the LLM (and sent to the web).
type FlowFinalEvent struct {
	FlowName string               `json:"flow_name"`
	Mermaid  string               `json:"mermaid"`
	Details  []FlowMessageDetail  `json:"details_map"`
	Mode     string               `json:"mode"` // "go_deterministic" (always now)
	Reasons  []string             `json:"reasons,omitempty"`
	Stats    *FlowValidationStats `json:"stats,omitempty"`
	// Annotations contains LLM-provided IP→NE mapping and stage segmentation.
	// May be nil if LLM parsing failed.
	Annotations *FlowAnnotationsV1 `json:"annotations,omitempty"`
}

type FlowValidationStats struct {
	InputPackets      int `json:"input_packets"`
	MermaidMessages   int `json:"mermaid_messages"`
	MappingEntries    int `json:"mapping_entries"`
	RemovedHeartbeats int `json:"removed_heartbeats"`
}

// FlowAnnotationsV1 is the structured JSON returned by LLM for IP→NE mapping and stage segmentation.
// The Mermaid diagram is always generated by Go; LLM only provides these annotations.
type FlowAnnotationsV1 struct {
	Version  string      `json:"version"` // should be "flow_annotations_v1"
	FlowName string      `json:"flow_name,omitempty"`
	IPMap    []IPMapping `json:"ip_map"`
	Stages   []FlowStage `json:"stages"`
}

// IPMapping maps an IP address to a network element role.
type IPMapping struct {
	IP         string  `json:"ip"`
	NE         string  `json:"ne"`                   // gNB, AMF, SMF, UPF, SGW, PGW, Unknown, etc.
	Confidence float64 `json:"confidence,omitempty"` // 0.0-1.0, optional
	Reason     string  `json:"reason,omitempty"`     // optional explanation
}

// FlowStage represents a logical stage/phase in the signaling flow.
// Each stage contains an explicit list of frames (packets) that belong to it.
type FlowStage struct {
	Name       string           `json:"name"`
	Frames     []FlowStageFrame `json:"frames"` // explicit list of frames in this stage
	Summary    string           `json:"summary,omitempty"`
	Confidence float64          `json:"confidence,omitempty"`
}

// FlowStageFrame represents a single frame within a stage.
// Number corresponds to frame.number from input JSON (Wireshark frame number).
type FlowStageFrame struct {
	Number string `json:"number"`          // frame.number from input JSON
	Title  string `json:"title,omitempty"` // message name for Mermaid label
	Note   string `json:"note,omitempty"`  // operation/effect description for Mermaid Note
}

// GetFlowBrief handles POST /api/jobs/{id}/flow/brief
func (h *Handler) GetFlowBrief(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowBriefRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	if req.Filter == "" {
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	// Get cached text or generate new
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to get packets: %v", err))
			return
		}
		if result.ExitCode != 0 {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("tshark error: %s", strings.TrimSpace(result.Stderr)))
			return
		}

		compactJSON, err = packet.SimplifyPacketsJSON(result.Stdout)
		if err != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Parse and analyze the packets
	brief, err := analyzePacketsForBrief(compactJSON)
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to analyze packets: %v", err))
		return
	}

	writeSuccess(w, brief)
}

// analyzePacketsForBrief extracts summary info from compact JSON
func analyzePacketsForBrief(compactJSON string) (*FlowBriefResponse, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return nil, fmt.Errorf("failed to parse JSON: %w", err)
	}

	brief := &FlowBriefResponse{
		PacketCount:      len(packets),
		ProtocolsPresent: []string{},
		KeyParams:        &KeyParamsCandidates{},
	}

	protocolSet := make(map[string]bool)
	imsiSet := make(map[string]bool)
	supiSet := make(map[string]bool)
	ueipSet := make(map[string]bool)
	teidSet := make(map[string]bool)
	seidSet := make(map[string]bool)
	qfiSet := make(map[string]bool)
	ranIdSet := make(map[string]bool)
	amfIdSet := make(map[string]bool)

	var firstTime, lastTime string
	var firstRelative, lastRelative string

	for _, pkt := range packets {
		// Extract frame info
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if t, ok := frame["time_absolute"].(string); ok && t != "" {
				if firstTime == "" {
					firstTime = t
				}
				lastTime = t
			}
			if t, ok := frame["time"].(string); ok && t != "" {
				if firstRelative == "" {
					firstRelative = t
				}
				lastRelative = t
			}
		}

		// Extract application layer protocols and params
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for proto, info := range app {
				protocolSet[proto] = true
				if infoMap, ok := info.(map[string]interface{}); ok {
					extractKeyParams(proto, infoMap, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet)
				}
			}
		}

		// Also check layers for IPs that might be UE IPs
		if layers, ok := pkt["layers"].(map[string]interface{}); ok {
			// We'll collect src/dst IPs but filter later for UE candidates
			// For now, just note them
			_ = layers
		}
	}

	// Build protocol list
	for proto := range protocolSet {
		brief.ProtocolsPresent = append(brief.ProtocolsPresent, proto)
	}
	sort.Strings(brief.ProtocolsPresent)

	// Build key params
	brief.KeyParams.IMSI = setToSlice(imsiSet)
	brief.KeyParams.SUPI = setToSlice(supiSet)
	brief.KeyParams.UEIP = setToSlice(ueipSet)
	brief.KeyParams.TEID = setToSlice(teidSet)
	brief.KeyParams.SEID = setToSlice(seidSet)
	brief.KeyParams.QFI = setToSlice(qfiSet)
	brief.KeyParams.RanUeNgapID = setToSlice(ranIdSet)
	brief.KeyParams.AmfUeNgapID = setToSlice(amfIdSet)

	// Calculate time range
	if firstTime != "" && lastTime != "" {
		startSec, _ := parseEpochTime(firstTime)
		endSec, _ := parseEpochTime(lastTime)
		durationMs := (endSec - startSec) * 1000

		brief.TimeRange = &TimeRange{
			Start:         firstTime,
			End:           lastTime,
			DurationMs:    durationMs,
			StartRelative: firstRelative,
			EndRelative:   lastRelative,
		}
	}

	return brief, nil
}

// extractKeyParams extracts key parameters from protocol info
func extractKeyParams(proto string, info map[string]interface{}, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet map[string]bool) {
	// Helper to add string to set
	addToSet := func(set map[string]bool, key string) {
		if v, ok := info[key].(string); ok && v != "" {
			set[v] = true
		}
	}

	switch proto {
	case "ngap":
		// Look for NAS info nested in ngap
		if nas, ok := info["nas"].(map[string]interface{}); ok {
			if msin, ok := nas["msin"].(string); ok && msin != "" {
				// Reconstruct IMSI from mcc+mnc+msin if available
				mcc, _ := nas["mcc"].(string)
				mnc, _ := nas["mnc"].(string)
				if mcc != "" && mnc != "" {
					imsiSet[mcc+mnc+msin] = true
				} else {
					imsiSet[msin] = true
				}
			}
			if supi, ok := nas["supi"].(string); ok && supi != "" {
				supiSet[supi] = true
			}
		}
		// Look in ies for IDs
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractFromIEs(ies, ranIdSet, amfIdSet, ueipSet, teidSet, seidSet, qfiSet)
		}

	case "nas-5gs":
		addToSet(supiSet, "supi")
		if msin, ok := info["msin"].(string); ok && msin != "" {
			mcc, _ := info["mcc"].(string)
			mnc, _ := info["mnc"].(string)
			if mcc != "" && mnc != "" {
				imsiSet[mcc+mnc+msin] = true
			}
		}

	case "pfcp":
		addToSet(seidSet, "seid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractPFCPParams(ies, ueipSet, teidSet, qfiSet, seidSet)
		}

	case "gtpv2":
		addToSet(teidSet, "teid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractGTPv2Params(ies, imsiSet, teidSet, ueipSet)
		}

	case "gtp":
		addToSet(teidSet, "teid")
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractGTPUParams(ies, qfiSet)
		}

	case "s1ap":
		if ies, ok := info["ies"].(map[string]interface{}); ok {
			extractS1APParams(ies, imsiSet, ueipSet)
		}
	}
}

// extractFromIEs recursively searches for key values in IE structures
func extractFromIEs(ies map[string]interface{}, ranIdSet, amfIdSet, ueipSet, teidSet, seidSet, qfiSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "ran-ue-ngap-id") || strings.Contains(keyLower, "ran_ue_ngap_id") {
					if s, ok := val.(string); ok && s != "" {
						ranIdSet[s] = true
					}
				}
				if strings.Contains(keyLower, "amf-ue-ngap-id") || strings.Contains(keyLower, "amf_ue_ngap_id") {
					if s, ok := val.(string); ok && s != "" {
						amfIdSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdu_address") || strings.Contains(keyLower, "ue_ip") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") || strings.Contains(keyLower, "f-teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "seid") || strings.Contains(keyLower, "f-seid") {
					if s, ok := val.(string); ok && s != "" {
						seidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractPFCPParams extracts PFCP-specific parameters
func extractPFCPParams(ies map[string]interface{}, ueipSet, teidSet, qfiSet, seidSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "ue_ip") || strings.Contains(keyLower, "pdu_address") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "seid") {
					if s, ok := val.(string); ok && s != "" {
						seidSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractGTPv2Params extracts GTPv2-specific parameters
func extractGTPv2Params(ies map[string]interface{}, imsiSet, teidSet, ueipSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "imsi") {
					if s, ok := val.(string); ok && s != "" {
						imsiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "teid") || strings.Contains(keyLower, "f-teid") {
					if s, ok := val.(string); ok && s != "" {
						teidSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdn_address") || strings.Contains(keyLower, "paa") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractGTPUParams extracts GTP-U specific parameters
func extractGTPUParams(ies map[string]interface{}, qfiSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "qfi") {
					if s, ok := val.(string); ok && s != "" {
						qfiSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// extractS1APParams extracts S1AP-specific parameters
func extractS1APParams(ies map[string]interface{}, imsiSet, ueipSet map[string]bool) {
	var search func(data interface{})
	search = func(data interface{}) {
		switch v := data.(type) {
		case map[string]interface{}:
			for key, val := range v {
				keyLower := strings.ToLower(key)
				if strings.Contains(keyLower, "imsi") {
					if s, ok := val.(string); ok && s != "" {
						imsiSet[s] = true
					}
				}
				if strings.Contains(keyLower, "pdn_address") {
					if s, ok := val.(string); ok && s != "" && isValidIP(s) {
						ueipSet[s] = true
					}
				}
				search(val)
			}
		case []interface{}:
			for _, item := range v {
				search(item)
			}
		}
	}
	search(ies)
}

// setToSlice converts a set to a sorted slice
func setToSlice(set map[string]bool) []string {
	if len(set) == 0 {
		return nil
	}
	result := make([]string, 0, len(set))
	for k := range set {
		result = append(result, k)
	}
	sort.Strings(result)
	return result
}

// parseEpochTime parses epoch time string to float64 seconds
func parseEpochTime(epochStr string) (float64, error) {
	// Format: "1703001234.123456789"
	return strconv.ParseFloat(epochStr, 64)
}

// isValidIP checks if a string looks like an IP address
func isValidIP(s string) bool {
	// Simple check: contains dots and only digits/dots (IPv4) or colons (IPv6)
	if strings.Contains(s, ".") {
		parts := strings.Split(s, ".")
		if len(parts) == 4 {
			for _, p := range parts {
				if _, err := strconv.Atoi(p); err != nil {
					return false
				}
			}
			return true
		}
	}
	if strings.Contains(s, ":") {
		// IPv6-like
		return true
	}
	return false
}

// GenerateFlow handles POST /api/jobs/{id}/flow/generate
func (h *Handler) GenerateFlow(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowGenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	if req.Filter == "" {
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	maxPackets := req.MaxEvents
	if maxPackets <= 0 {
		maxPackets = 1000 // default
	}

	// Get cached text or generate new (same data source as "复制JSON" button)
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to get packets: %v", err))
			return
		}
		if result.ExitCode != 0 {
			writeError(w, http.StatusInternalServerError, fmt.Sprintf("tshark error: %s", strings.TrimSpace(result.Stderr)))
			return
		}

		var err2 error
		compactJSON, err2 = packet.SimplifyPacketsJSON(result.Stdout)
		if err2 != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Limit the number of packets sent to LLM if needed
	limitedJSON, _, err := limitPacketsJSON(compactJSON, maxPackets)
	if err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to process packets: %v", err))
		return
	}

	// Extract key params from compactJSON for response
	keyParams := extractKeyParamsFromJSON(compactJSON)

	// Filter heartbeat packets to make LLM input deterministic
	llmInputJSON, removedHeartbeats, err := filterHeartbeatPacketsJSON(limitedJSON)
	if err != nil {
		llmInputJSON = limitedJSON
		removedHeartbeats = 0
	}

	// Count packets in llmInputJSON and build valid frame numbers set
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(llmInputJSON), &packets); err != nil {
		writeError(w, http.StatusInternalServerError, fmt.Sprintf("failed to parse packets: %v", err))
		return
	}
	packetCount := len(packets)

	// Build valid frame numbers set
	validFrameNumbers := make(map[string]bool)
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok && num != "" {
				validFrameNumbers[num] = true
			}
		}
	}

	log.Printf("[FlowGenerate] Job %s: %d packets after filtering (removed %d heartbeats)", id, packetCount, removedHeartbeats)

	// Call Moonshot API to get annotations only (IP→NE mapping, stages)
	// annotations may be nil if LLM fails - that's OK, we still generate deterministic Mermaid
	annotations := h.callMoonshotForAnnotations(llmInputJSON, packetCount, validFrameNumbers)

	// Determine which JSON to use for rendering
	// If annotations are valid, filter to only selected frames (subset rendering)
	// Otherwise, use full llmInputJSON (fallback to all packets)
	renderJSON := llmInputJSON
	flowName := "信令流程图"

	if annotations != nil {
		flowName = annotations.FlowName
		// Collect selected frames from all stages
		selectedFrames := collectSelectedFramesSet(annotations.Stages)
		if len(selectedFrames) > 0 {
			filteredJSON, filteredCount, err := filterPacketsByFrameNumbers(llmInputJSON, selectedFrames)
			if err != nil {
				log.Printf("[FlowGenerate] Warning: failed to filter packets, using full set: %v", err)
			} else if filteredCount > 0 {
				renderJSON = filteredJSON
				log.Printf("[FlowGenerate] Filtered to %d packets based on annotations (from %d)", filteredCount, packetCount)
			}
		}
	}

	// Generate Mermaid deterministically from Go using annotations
	mermaid := buildDeterministicMermaid(renderJSON, flowName, annotations)

	// Build details mapping (guaranteed 1:1 with Mermaid)
	details := buildDetailsMapping(renderJSON)

	log.Printf("[FlowGenerate] Generated Mermaid with %d messages, annotations=%v", len(details), annotations != nil)

	writeSuccess(w, &FlowGenerateResponse{
		FlowName:    flowName,
		Mermaid:     mermaid,
		KeyParams:   keyParams,
		Details:     details,
		InputJSON:   renderJSON, // Return the subset JSON that matches the diagram
		Annotations: annotations,
	})
}

// limitPacketsJSON limits the number of packets in JSON array
func limitPacketsJSON(compactJSON string, maxPackets int) (string, int, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return "", 0, fmt.Errorf("failed to parse JSON: %w", err)
	}

	if len(packets) > maxPackets {
		packets = packets[:maxPackets]
	}

	result, err := json.Marshal(packets)
	if err != nil {
		return "", 0, fmt.Errorf("failed to marshal limited packets: %w", err)
	}

	return string(result), len(packets), nil
}

// extractKeyParamsFromJSON extracts key parameters from compactJSON
func extractKeyParamsFromJSON(compactJSON string) *KeyParamsCandidates {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return &KeyParamsCandidates{}
	}

	keyParams := &KeyParamsCandidates{}
	imsiSet := make(map[string]bool)
	supiSet := make(map[string]bool)
	ueipSet := make(map[string]bool)
	teidSet := make(map[string]bool)
	seidSet := make(map[string]bool)
	qfiSet := make(map[string]bool)
	ranIdSet := make(map[string]bool)
	amfIdSet := make(map[string]bool)

	for _, pkt := range packets {
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for proto, info := range app {
				if infoMap, ok := info.(map[string]interface{}); ok {
					extractKeyParams(proto, infoMap, imsiSet, supiSet, ueipSet, teidSet, seidSet, qfiSet, ranIdSet, amfIdSet)
				}
			}
		}
	}

	keyParams.IMSI = setToSlice(imsiSet)
	keyParams.SUPI = setToSlice(supiSet)
	keyParams.UEIP = setToSlice(ueipSet)
	keyParams.TEID = setToSlice(teidSet)
	keyParams.SEID = setToSlice(seidSet)
	keyParams.QFI = setToSlice(qfiSet)
	keyParams.RanUeNgapID = setToSlice(ranIdSet)
	keyParams.AmfUeNgapID = setToSlice(amfIdSet)

	return keyParams
}

// buildDetailsMapping builds the idx->originNumber mapping from input packets JSON.
// This is the fallback method when LLM doesn't provide a MAPPING section.
// It assumes sequential ordering: Mermaid autonumber idx corresponds to packet array index.
// idx and frame are both 1-based (matching Mermaid autonumber which starts at 1).
// originNumber is the pcap frame.number (Wireshark frame number).
func buildDetailsMapping(compactJSON string) []FlowMessageDetail {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return nil
	}

	details := make([]FlowMessageDetail, 0, len(packets))
	for i, pkt := range packets {
		detail := FlowMessageDetail{
			Idx:   i + 1, // 1-based index matching Mermaid autonumber
			Frame: i + 1, // 1-based position in input array
		}

		// Extract frame.number as originNumber
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok {
				detail.OriginNumber = num
			}
		}

		details = append(details, detail)
	}

	return details
}

// countHeartbeatMessages counts PFCP Heartbeat messages in the packet JSON.
func countHeartbeatMessages(compactJSON string) int {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return 0
	}

	count := 0
	for _, pkt := range packets {
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			if pfcp, ok := app["pfcp"].(map[string]interface{}); ok {
				// Check message field for Heartbeat
				if msg, ok := pfcp["message"].(string); ok {
					if strings.Contains(strings.ToLower(msg), "heartbeat") {
						count++
						continue
					}
				}
				// Check message_type field (1=Heartbeat Request, 2=Heartbeat Response)
				if msgType, ok := pfcp["message_type"].(string); ok {
					if msgType == "1" || msgType == "2" {
						count++
					}
				}
			}
		}
	}
	return count
}

// filterHeartbeatPacketsJSON removes PFCP heartbeat packets from the JSON array.
// This is important for absolute consistency: what we send to the LLM must be the same
// thing we later correlate in the web UI (and we don't want the model to decide "what is heartbeat").
func filterHeartbeatPacketsJSON(compactJSON string) (string, int, error) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return compactJSON, 0, err
	}

	isHeartbeat := func(pkt map[string]interface{}) bool {
		app, ok := pkt["application"].(map[string]interface{})
		if !ok {
			return false
		}
		pfcp, ok := app["pfcp"].(map[string]interface{})
		if !ok {
			return false
		}
		if msg, ok := pfcp["message"].(string); ok {
			if strings.Contains(strings.ToLower(msg), "heartbeat") {
				return true
			}
		}
		if msgType, ok := pfcp["message_type"].(string); ok {
			if msgType == "1" || msgType == "2" {
				return true
			}
		}
		return false
	}

	filtered := make([]map[string]interface{}, 0, len(packets))
	removed := 0
	for _, pkt := range packets {
		if isHeartbeat(pkt) {
			removed++
			continue
		}
		filtered = append(filtered, pkt)
	}

	out, err := json.Marshal(filtered)
	if err != nil {
		return compactJSON, 0, err
	}
	return string(out), removed, nil
}

// countMermaidMessages counts Mermaid sequenceDiagram message arrows in a best-effort way.
func countMermaidMessages(mermaid string) int {
	if strings.TrimSpace(mermaid) == "" {
		return 0
	}
	count := 0
	lines := strings.Split(mermaid, "\n")
	for _, raw := range lines {
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}
		if strings.HasPrefix(line, "%%") {
			continue
		}
		if strings.HasPrefix(line, "Note ") {
			continue
		}
		// A message line should contain ":" and an arrow.
		if !strings.Contains(line, ":") {
			continue
		}
		if strings.Contains(line, "->>") || strings.Contains(line, "-->>") || strings.Contains(line, "->") || strings.Contains(line, "-->") {
			count++
		}
	}
	return count
}

// validateFlowLLMParsed enforces strict consistency between:
// - input packets (exact JSON sent to LLM)
// - Mermaid message count
// - MAPPING (idx -> frame.number)
//
// If validation fails, caller should fallback to deterministic full diagram.
func validateFlowLLMParsed(compactJSON string, parsed flowLLMParsed, removedHeartbeats int) (bool, []string, FlowValidationStats) {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return false, []string{"input_json解析失败"}, FlowValidationStats{RemovedHeartbeats: removedHeartbeats}
	}
	inputCount := len(packets)

	validFrames := make(map[string]struct{}, inputCount)
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok {
				validFrames[num] = struct{}{}
			}
		}
	}

	mermaidCount := countMermaidMessages(parsed.Mermaid)
	mappingCount := len(parsed.Mapping)

	stats := FlowValidationStats{
		InputPackets:      inputCount,
		MermaidMessages:   mermaidCount,
		MappingEntries:    mappingCount,
		RemovedHeartbeats: removedHeartbeats,
	}

	var reasons []string
	if mermaidCount <= 0 {
		reasons = append(reasons, "Mermaid消息数=0")
	}
	// Since we pre-filter heartbeat packets, we expect 1 message per packet.
	if inputCount > 0 && mermaidCount != inputCount {
		reasons = append(reasons, fmt.Sprintf("Mermaid消息数(%d) != 输入包数(%d)", mermaidCount, inputCount))
	}
	if mappingCount != mermaidCount {
		reasons = append(reasons, fmt.Sprintf("Mapping条数(%d) != Mermaid消息数(%d)", mappingCount, mermaidCount))
	}

	// idx coverage and uniqueness
	idxToFrame := make(map[int]string, mappingCount)
	for _, e := range parsed.Mapping {
		if e.Idx <= 0 {
			reasons = append(reasons, fmt.Sprintf("存在非法idx(%d)", e.Idx))
			continue
		}
		if _, exists := idxToFrame[e.Idx]; exists {
			reasons = append(reasons, fmt.Sprintf("存在重复idx(%d)", e.Idx))
			continue
		}
		idxToFrame[e.Idx] = e.FrameNumber
	}
	if mermaidCount > 0 {
		for i := 1; i <= mermaidCount; i++ {
			if _, ok := idxToFrame[i]; !ok {
				reasons = append(reasons, fmt.Sprintf("缺少idx=%d", i))
				break
			}
		}
	}

	// frame existence + strict monotonicity by idx (prompt requires strict frame.number order)
	last := -1
	for i := 1; i <= mermaidCount; i++ {
		f := idxToFrame[i]
		if f == "" {
			continue
		}
		if _, ok := validFrames[f]; !ok {
			reasons = append(reasons, fmt.Sprintf("frame不存在(%s)", f))
			break
		}
		n, err := strconv.Atoi(f)
		if err != nil {
			reasons = append(reasons, fmt.Sprintf("frame非数字(%s)", f))
			break
		}
		if last != -1 && n <= last {
			reasons = append(reasons, fmt.Sprintf("frame未严格递增(%d -> %d)", last, n))
			break
		}
		last = n
	}

	return len(reasons) == 0, reasons, stats
}

func safeOneLine(s string, max int) string {
	out := strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	out = strings.Join(strings.Fields(out), " ")
	if max > 0 && len(out) > max {
		return out[:max-3] + "..."
	}
	return out
}

func getString(m map[string]interface{}, key string) string {
	if v, ok := m[key]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

func inferRoleFromEndpoint(ip, port, proto string) string {
	if ip == "" {
		return "?"
	}
	if proto == "sctp" && port == "38412" {
		return "AMF"
	}
	if proto == "udp" && port == "8805" {
		return "SMF/UPF"
	}
	if proto == "udp" && port == "2123" {
		return "SGW/PGW"
	}
	return ip
}

func buildPacketTitle(pkt map[string]interface{}) string {
	frameNum := ""
	if frame, ok := pkt["frame"].(map[string]interface{}); ok {
		frameNum = getString(frame, "number")
	}

	app, _ := pkt["application"].(map[string]interface{})
	if app != nil {
		if ngap, ok := app["ngap"].(map[string]interface{}); ok {
			proc := getString(ngap, "procedure")
			if proc == "" {
				proc = getString(ngap, "procedureCode")
				if proc != "" {
					proc = "NGAP(" + proc + ")"
				}
			}
			if proc == "" {
				proc = "NGAP"
			}
			return safeOneLine("["+frameNum+"] "+proc, 80)
		}
		if nas, ok := app["nas-5gs"].(map[string]interface{}); ok {
			mm := getString(nas, "mm_message")
			sm := getString(nas, "sm_message")
			title := mm
			if title == "" {
				title = sm
			}
			if title == "" {
				title = "NAS-5GS"
			}
			return safeOneLine("["+frameNum+"] "+title, 80)
		}
		if pfcp, ok := app["pfcp"].(map[string]interface{}); ok {
			msg := getString(pfcp, "message")
			if msg == "" {
				msg = getString(pfcp, "message_type")
				if msg != "" {
					msg = "PFCP(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "PFCP"
			}
			return safeOneLine("["+frameNum+"] "+msg, 80)
		}
		if gtpv2, ok := app["gtpv2"].(map[string]interface{}); ok {
			msg := getString(gtpv2, "message")
			if msg == "" {
				msg = getString(gtpv2, "message_type")
				if msg != "" {
					msg = "GTPv2(" + msg + ")"
				}
			}
			if msg == "" {
				msg = "GTPv2"
			}
			return safeOneLine("["+frameNum+"] "+msg, 80)
		}
		if s1ap, ok := app["s1ap"].(map[string]interface{}); ok {
			proc := getString(s1ap, "procedure")
			if proc == "" {
				proc = "S1AP"
			}
			return safeOneLine("["+frameNum+"] "+proc, 80)
		}
	}
	if frameNum != "" {
		return safeOneLine("Frame "+frameNum, 80)
	}
	return "Frame"
}

// buildDeterministicMermaid builds a guaranteed-consistent sequence diagram from the exact input JSON.
// It creates exactly one Mermaid message per packet in the same order, so message count == mapping count == input packets.
// If annotations are provided, uses ip_map for participant naming and inserts stage notes.
//
// NEW DESIGN (IP-keyed nodes):
// - Participants are keyed by unique IP address (not by "Role(IP)" string matching)
// - Message direction strictly follows packet's src_ip → dst_ip
// - ip_map from annotations provides display names; unknown IPs show raw IP
// - No port-based role inference for naming (avoids ambiguity)
func buildDeterministicMermaid(compactJSON string, flowName string, ann *FlowAnnotationsV1) string {
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return "sequenceDiagram\n    autonumber\n"
	}

	// Build IP→NE lookup from annotations
	ipToNE := make(map[string]string)
	if ann != nil {
		for _, m := range ann.IPMap {
			if m.IP != "" && m.NE != "" {
				ipToNE[m.IP] = m.NE
			}
		}
	}

	// Build frame→info lookups from annotations
	// frameToStage: first frame of each stage → stage (for inserting stage notes)
	// frameToInfo: frame.number → FlowStageFrame (for title/note overrides)
	frameToStage := make(map[string]*FlowStage)
	frameToInfo := make(map[string]*FlowStageFrame)
	if ann != nil {
		for i := range ann.Stages {
			s := &ann.Stages[i]
			if len(s.Frames) > 0 {
				// First frame of stage triggers the stage note
				frameToStage[s.Frames[0].Number] = s
			}
			// Build frame info lookup
			for j := range s.Frames {
				f := &s.Frames[j]
				frameToInfo[f.Number] = f
			}
		}
	}

	// Use flow_name from annotations if available
	if ann != nil && ann.FlowName != "" {
		flowName = ann.FlowName
	}

	// ========== NEW: IP-keyed participant collection ==========
	// ipNode holds info for a unique IP participant
	type ipNode struct {
		IP         string // unique key
		Role       string // from ipToNE, or "Unknown"
		FirstSeen  int    // order of first appearance (0-based)
		GroupIndex int    // index in roleOrder for sorting
	}

	// Collect unique IPs in first-seen order
	ipNodes := make(map[string]*ipNode) // key = IP
	ipOrder := make([]string, 0, 8)     // IPs in first-seen order
	seenCount := 0

	ensureIP := func(ip string) {
		if ip == "" {
			ip = "?"
		}
		if _, exists := ipNodes[ip]; exists {
			return
		}
		// Get role from annotations, default to "Unknown"
		role := "Unknown"
		if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
			role = ne
		}
		ipNodes[ip] = &ipNode{
			IP:         ip,
			Role:       role,
			FirstSeen:  seenCount,
			GroupIndex: getRoleGroupIndex(role),
		}
		ipOrder = append(ipOrder, ip)
		seenCount++
	}

	// Message structure: store IPs directly, not derived names
	type Msg struct {
		FromIP      string
		ToIP        string
		Title       string
		FrameNumber string // frame.number for looking up stage/frame info
	}
	msgs := make([]Msg, 0, len(packets))

	for _, pkt := range packets {
		layers, _ := pkt["layers"].(map[string]interface{})
		srcIP := ""
		dstIP := ""
		if layers != nil {
			srcIP = getString(layers, "src_ip")
			dstIP = getString(layers, "dst_ip")
		}
		if srcIP == "" {
			srcIP = "?"
		}
		if dstIP == "" {
			dstIP = "?"
		}

		// Get frame.number
		frameNum := ""
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			frameNum = getString(frame, "number")
		}

		// Register IPs as participants (in first-seen order)
		ensureIP(srcIP)
		ensureIP(dstIP)

		// Determine title: prefer LLM-provided title if available
		title := buildPacketTitle(pkt)
		if info, ok := frameToInfo[frameNum]; ok && info.Title != "" {
			title = fmt.Sprintf("[%s] %s", frameNum, info.Title)
		}

		msgs = append(msgs, Msg{FromIP: srcIP, ToIP: dstIP, Title: title, FrameNumber: frameNum})
	}

	// ========== Sort IPs by role order, then first-seen within same role ==========
	sortedIPs := make([]string, len(ipOrder))
	copy(sortedIPs, ipOrder)
	sort.SliceStable(sortedIPs, func(i, j int) bool {
		ni, nj := ipNodes[sortedIPs[i]], ipNodes[sortedIPs[j]]
		if ni.GroupIndex != nj.GroupIndex {
			return ni.GroupIndex < nj.GroupIndex
		}
		return ni.FirstSeen < nj.FirstSeen
	})

	// ========== Generate display names with numbering for duplicate roles ==========
	// Count how many IPs per role
	roleCounts := make(map[string]int)
	for _, ip := range sortedIPs {
		roleCounts[ipNodes[ip].Role]++
	}

	// Build display name and ID for each IP
	idByIP := make(map[string]string, len(sortedIPs))      // IP → "P1", "P2", ...
	displayByIP := make(map[string]string, len(sortedIPs)) // IP → "AMF(10.x)" or "10.x"
	roleSeq := make(map[string]int)                        // current sequence number for each role

	for i, ip := range sortedIPs {
		node := ipNodes[ip]
		idByIP[ip] = fmt.Sprintf("P%d", i+1)

		if node.Role == "Unknown" || node.Role == "?" {
			// Unknown role: just show IP
			displayByIP[ip] = ip
		} else if roleCounts[node.Role] > 1 {
			// Multiple IPs with same role: add number
			roleSeq[node.Role]++
			displayByIP[ip] = fmt.Sprintf("%s%d(%s)", node.Role, roleSeq[node.Role], ip)
		} else {
			// Single IP for this role
			displayByIP[ip] = fmt.Sprintf("%s(%s)", node.Role, ip)
		}
	}

	// ========== Build Mermaid output ==========
	var b strings.Builder
	b.WriteString("sequenceDiagram\n")
	b.WriteString("    autonumber\n")
	if strings.TrimSpace(flowName) != "" {
		b.WriteString("    %% ")
		b.WriteString(safeOneLine(flowName, 120))
		b.WriteString("\n")
	}
	for _, ip := range sortedIPs {
		b.WriteString("    participant ")
		b.WriteString(idByIP[ip])
		b.WriteString(" as ")
		b.WriteString(safeOneLine(displayByIP[ip], 60))
		b.WriteString("\n")
	}
	b.WriteString("\n")

	// Get first and last participant IDs for Note over
	firstPID := "P1"
	lastPID := fmt.Sprintf("P%d", len(sortedIPs))
	if len(sortedIPs) == 0 {
		lastPID = "P1"
	}

	for _, m := range msgs {
		// Insert stage note if this frame is the first of a stage
		if stage, ok := frameToStage[m.FrameNumber]; ok {
			b.WriteString("\n    Note over ")
			b.WriteString(firstPID)
			b.WriteString(",")
			b.WriteString(lastPID)
			b.WriteString(": === ")
			b.WriteString(safeOneLine(stage.Name, 40))
			if stage.Summary != "" {
				b.WriteString(" === ")
				b.WriteString(safeOneLine(stage.Summary, 60))
			}
			b.WriteString("\n\n")
		}

		// Use IP directly to get participant ID (no string matching needed)
		fromID := idByIP[m.FromIP]
		toID := idByIP[m.ToIP]
		if fromID == "" {
			fromID = "P1"
		}
		if toID == "" {
			toID = "P1"
		}
		b.WriteString("    ")
		b.WriteString(fromID)
		b.WriteString("->>")
		b.WriteString(toID)
		b.WriteString(": ")
		b.WriteString(safeOneLine(m.Title, 120))
		b.WriteString("\n")

		// Insert frame note if available
		if info, ok := frameToInfo[m.FrameNumber]; ok && info.Note != "" {
			b.WriteString("    Note over ")
			b.WriteString(fromID)
			b.WriteString(",")
			b.WriteString(toID)
			b.WriteString(": ")
			b.WriteString(safeOneLine(info.Note, 80))
			b.WriteString("\n")
		}
	}
	return b.String()
}

// getRoleForIP returns the network element role for an IP from annotations.
// Returns "Unknown" if IP is not found in the annotation map.
// This is used for IP-keyed participant identification.
func getRoleForIP(ip string, ipToNE map[string]string) string {
	if ip == "" {
		return "Unknown"
	}
	if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
		return ne
	}
	return "Unknown"
}

// getDisplayNameForIP returns the display name for an IP participant.
// If role is known from annotations: "Role(IP)" or "Role{n}(IP)" for multiple same-role IPs.
// If role is unknown: just "IP".
// Parameters:
// - ip: the IP address
// - role: the role from annotations (or "Unknown")
// - seq: sequence number for this role (1-based, 0 means don't add number)
// - needsNumber: whether to add sequence number (true if multiple IPs have same role)
func getDisplayNameForIP(ip, role string, seq int, needsNumber bool) string {
	if ip == "" {
		return "?"
	}
	if role == "Unknown" || role == "" {
		return ip
	}
	if needsNumber && seq > 0 {
		return fmt.Sprintf("%s%d(%s)", role, seq, ip)
	}
	return fmt.Sprintf("%s(%s)", role, ip)
}

// inferRoleWithAnnotations infers the network element role from IP, using annotations if available.
// DEPRECATED: This function is kept for backward compatibility.
// New code should use getRoleForIP and getDisplayNameForIP instead.
// No longer falls back to port-based inference (per IP-keyed design).
func inferRoleWithAnnotations(ip, port, proto string, ipToNE map[string]string) string {
	if ip == "" {
		return "?"
	}

	// Check annotations - return display name if found
	if ne, ok := ipToNE[ip]; ok && ne != "" && ne != "Unknown" {
		return fmt.Sprintf("%s(%s)", ne, ip)
	}

	// No port-based fallback: just return raw IP for unknown
	return ip
}

// buildDetailsMappingFromLLM builds the details mapping using the LLM-provided MAPPING section.
// This provides accurate correlation when LLM skips heartbeat messages or reorders packets.
// Falls back to sequential mapping if LLM mapping is empty.
func buildDetailsMappingFromLLM(compactJSON string, llmMapping []LLMMappingEntry) []FlowMessageDetail {
	if len(llmMapping) == 0 {
		// Fallback to sequential mapping
		return buildDetailsMapping(compactJSON)
	}

	// Ensure deterministic order by idx
	mapping := make([]LLMMappingEntry, len(llmMapping))
	copy(mapping, llmMapping)
	sort.Slice(mapping, func(i, j int) bool { return mapping[i].Idx < mapping[j].Idx })

	// Build a map from frame.number to array index for quick lookup
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return nil
	}

	frameToArrayIdx := make(map[string]int)
	for i, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok {
				frameToArrayIdx[num] = i + 1 // 1-based
			}
		}
	}

	// Build details from LLM mapping
	details := make([]FlowMessageDetail, 0, len(mapping))
	for _, entry := range mapping {
		arrayIdx := frameToArrayIdx[entry.FrameNumber]
		if arrayIdx == 0 {
			// Frame number not found in packets, use idx as fallback
			arrayIdx = entry.Idx
		}
		details = append(details, FlowMessageDetail{
			Idx:          entry.Idx,
			Frame:        arrayIdx,
			OriginNumber: entry.FrameNumber,
		})
	}

	return details
}

// buildFlowAnnotationsPrompt builds the prompt for LLM to output structured JSON annotations only.
// The LLM no longer generates Mermaid; it only provides IP→NE mappings and stage segmentation with explicit frames.
// Go will use these annotations to generate a deterministic Mermaid diagram.
func buildFlowAnnotationsPrompt(compactJSON string, packetCount int) string {
	return fmt.Sprintf(`你是一个5G/LTE核心网信令分析专家。请根据以下数据包信息，输出一个 **纯 JSON 对象**，用于标注IP地址与网元的对应关系，以及信令流程的阶段划分。

**【极其重要 - 完整性要求】**
⚠️ **必须包含所有数据包，一个都不能遗漏！输入共 %d 条！**
⚠️ **stages 中所有 frames 数组的元素总数必须等于输入的数据包总数！**
⚠️ **即使是"重复"的消息，也必须全部包含，不能合并或省略！**
⚠️ **只输出单个JSON对象，不要输出任何其他内容！**

数据包JSON（已过滤心跳消息，共 %d 条）：
%s

数据结构说明：
- frame: 帧信息（number=帧序号，这是唯一标识符）
- layers: 网络层信息（src_ip=源IP, dst_ip=目的IP, proto=传输协议, src_port/dst_port=端口）
- application: 应用层协议详情
  - ngap: gNB与AMF之间的N2接口协议
  - pfcp: SMF与UPF之间的N4接口协议
  - gtpv2: GTP控制面协议
  - s1ap: 4G LTE的eNB与MME之间的S1接口协议
  - diameter: 3GPP Diameter协议
  - http2: SBI接口的HTTP/2消息
  - sip: IMS信令

**你的任务**：
1. 分析所有数据包，识别每个IP地址对应的网元角色
2. 将信令流程划分为逻辑阶段（如：注册、认证、PDU会话建立，会话更新等）
3. 为每个阶段明确列出属于该阶段的帧（通过 frame.number 标识）
4. 为每个帧提供 title（消息名称，注意一定是完整的标准的消息类型名称，如果是pfcp消息，一定要在消息的后面加上DNN,比如PFCP Session Establishment Request(DNN: ctnet)）和 note（操作说明/关键参数）
5. **【必须】确保所有数据包都被分配到某个阶段中，不能遗漏任何一条！**
6. 输出一个严格符合以下schema的JSON对象

**JSON Schema**：
{
  "version": "flow_annotations_v1",
  "flow_name": "简短的流程名称",
  "ip_map": [
    {
      "ip": "IP地址",
      "ne": "网元类型"
    }
  ],
  "stages": [
    {
      "name": "阶段名称",
      "summary": "阶段简述",
      "frames": [
        {
          "number": "帧序号",
          "title": "消息名称，注意一定是完整的标准的消息类型名称",
          "note": "操作说明/关键参数/参数尽可能完整准确"
        }
      ]
    }
  ]
}

**字段说明**：
- version: 固定为 "flow_annotations_v1"
- flow_name: 流程名称，简洁描述（可包含SUPI/DNN等关键信息）
- ip_map: IP地址到网元的映射数组
  - ip: 必填，IP地址字符串
  - ne: 必填，网元类型。只允许以下值：gNB, eNB, AMF, MME, SMF, PGW, UPF, SGW, PCRF, HSS, UDM, AUSF, Unknown
- stages: 阶段数组（按流程顺序排列）
  - name: 必填，阶段名称（如"5G注册"、"PDU会话建立(DNN:ctnet)"）
  - summary: 可选，该阶段的简短总结，尽可能详细准确
  - frames: 必填，该阶段包含的帧列表（按时间顺序）
    - number: 必填，帧序号（必须是输入JSON中存在的 frame.number 值）
    - title: 必填，消息名称（用于流程图显示，如"InitialUEMessage"，注意一定是完整的标准的消息类型名称，如果是pfcp消息，一定要在消息的后面加上DNN,比如PFCP Session Establishment Request(DNN: ctnet)）
    - note: 可选，该消息的关键操作/参数说明（如"分配UE IP: 10.57.1.100"，分配的FTEID、"建立PDR/FAR规则"，参数尽可能完整准确）

**网元识别规则**（参考）：
- SCTP端口38412 → NGAP接口 → 一端是gNB，另一端是AMF
- UDP端口8805 → PFCP接口 → 一端是SMF，另一端是UPF
- UDP端口2123 → GTPv2-C接口 → SGW/PGW
- 分析消息方向：如gNB发送InitialUEMessage到AMF

**阶段划分建议**（仅供参考）：
- 5G注册流程：Registration Request → Registration Complete
- 认证阶段：Authentication Request/Response
- 安全模式：Security Mode Command/Complete
- PDU会话建立：PDU Session Establishment（按DNN/SessionID分开）
- PFCP会话管理：Session Establishment/Modification/Deletion

**示例输出**（请输出类似格式的JSON）：
{"version":"flow_annotations_v1","flow_name":"5G注册与PDU会话建立","ip_map":[{"ip":"10.18.11.23","ne":"gNB","reason":"NGAP发送方"},{"ip":"10.18.11.20","ne":"AMF","reason":"NGAP端口38412"},{"ip":"127.0.0.3","ne":"SMF","reason":"PFCP端口8805"},{"ip":"127.0.0.5","ne":"UPF","reason":"PFCP端口8805"}],"stages":[{"name":"5G注册","summary":"UE注册到5G核心网","frames":[{"number":"1001","title":"Registration Request","note":"SUPI: 460110000000001"},{"number":"1002","title":"Authentication Request","note":""},{"number":"1003","title":"Authentication Response","note":""},{"number":"1005","title":"Security Mode Command","note":""},{"number":"1006","title":"Security Mode Complete","note":""},{"number":"1007","title":"Registration Accept","note":"5G-GUTI分配"},{"number":"1008","title":"Initial Context Setup Response","note":""},{"number":"1009","title":"Registration Complete","note":""}]},{"name":"PDU会话建立(DNN:ctnet)","summary":"建立ctnet数据会话","frames":[{"number":"1015","title":"PDU Session Est Request","note":"DNN: ctnet, SST: 1"},{"number":"1016","title":"PFCP Session Est Req","note":"创建PDR/FAR"},{"number":"1017","title":"PFCP Session Est Resp","note":"成功"},{"number":"1018","title":"PDU Session Est Accept","note":"UE IP: 10.57.1.100"},{"number":"1019","title":"PDU Session Resource Setup Resp","note":""}]}]}

**【注意事项】**：
1. frames 中的 number 必须是输入JSON中实际存在的 frame.number 值
2. 每个帧的 title ，适合在流程图中显示，注意一定是完整的标准的消息类型名称
3. note 用于记录该消息的关键信息，可以为空，参数尽可能完整准确
4. **【必须】所有数据包都必须包含在 stages 的 frames 中，不能遗漏任何一条！**
5. 同一个帧只能属于一个阶段
6. 即使消息类型相同，也必须分别列出每一条，不能合并

**【最后检查】生成JSON前请确认：**
- stages 中所有 frames 的元素总数 = 输入的数据包总数（%d）
- 没有遗漏任何一条数据包
- 没有合并或省略重复的消息

**【再次强调】只输出一个纯JSON对象，不要有任何其他字符！**`, packetCount, packetCount, compactJSON, packetCount)
}

// callMoonshotForAnnotations calls Moonshot API to get structured annotations (IP→NE mapping, stages).
// Returns nil annotations (not error) if LLM fails or returns invalid JSON - the caller can still
// generate a deterministic Mermaid diagram without annotations.
// validFrameNumbers is a set of valid frame.number strings from input packets.
func (h *Handler) callMoonshotForAnnotations(compactJSON string, packetCount int, validFrameNumbers map[string]bool) *FlowAnnotationsV1 {
	log.Printf("[FlowAnnotations] ========== CALLING LLM FOR ANNOTATIONS START ==========")
	log.Printf("[FlowAnnotations] Input: packetCount=%d, compactJSON size=%d bytes, valid frame numbers=%d",
		packetCount, len(compactJSON), len(validFrameNumbers))

	client := h.getMoonshotClient()
	if client == nil {
		log.Printf("[FlowAnnotations] Moonshot API key not configured, skipping annotations")
		log.Printf("[FlowAnnotations] ========== CALLING LLM FOR ANNOTATIONS END (no client) ==========")
		return nil
	}

	prompt := buildFlowAnnotationsPrompt(compactJSON, packetCount)
	log.Printf("[FlowAnnotations] Built prompt: size=%d bytes", len(prompt))

	// Log a simplified summary of the input packets
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err == nil {
		log.Printf("[FlowAnnotations] Input packets summary (%d packets):", len(packets))
		previewCount := len(packets)
		if previewCount > 10 {
			previewCount = 10
		}
		for i := 0; i < previewCount; i++ {
			pkt := packets[i]
			frameNum := ""
			if frame, ok := pkt["frame"].(map[string]interface{}); ok {
				frameNum = getString(frame, "number")
			}
			proto := ""
			msgType := ""
			if app, ok := pkt["application"].(map[string]interface{}); ok {
				for protoName, protoData := range app {
					proto = protoName
					if pd, ok := protoData.(map[string]interface{}); ok {
						if procedure, ok := pd["procedure"].(string); ok {
							msgType = procedure
						} else if message, ok := pd["message"].(string); ok {
							msgType = message
						} else if mmMsg, ok := pd["mm_message"].(string); ok {
							msgType = mmMsg
						} else if smMsg, ok := pd["sm_message"].(string); ok {
							msgType = smMsg
						}
					}
					break
				}
			}
			log.Printf("[FlowAnnotations]   Packet[%d]: frame=%s, proto=%s, msg=%s",
				i, frameNum, proto, safeOneLine(msgType, 50))
		}
		if len(packets) > 10 {
			log.Printf("[FlowAnnotations]   ... (%d more packets)", len(packets)-10)
		}
	}

	startTime := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	log.Printf("[FlowAnnotations] Calling Moonshot API...")
	response, err := client.ChatCompletion(ctx, prompt)
	elapsed := time.Since(startTime)

	if err != nil {
		log.Printf("[FlowAnnotations] ERROR: Moonshot API call failed after %v: %v", elapsed, err)
		log.Printf("[FlowAnnotations] ========== CALLING LLM FOR ANNOTATIONS END (error) ==========")
		return nil
	}

	log.Printf("[FlowAnnotations] Moonshot API call succeeded in %v, response size: %d bytes", elapsed, len(response))

	// Log the raw response for debugging
	log.Printf("[FlowAnnotations] Raw LLM response preview: %s", truncateForLog(response, 800))
	if len(response) > 800 {
		log.Printf("[FlowAnnotations] Raw LLM response (last 300 chars): ...%s", response[len(response)-300:])
	}

	// Parse JSON response
	ann, err := parseFlowAnnotationsJSON(response, validFrameNumbers)
	if err != nil {
		log.Printf("[FlowAnnotations] Failed to parse annotations JSON: %v", err)
		log.Printf("[FlowAnnotations] ========== CALLING LLM FOR ANNOTATIONS END (parse error) ==========")
		return nil
	}

	log.Printf("[FlowAnnotations] Successfully parsed annotations: flow_name=%q, ip_map=%d entries, stages=%d entries",
		ann.FlowName, len(ann.IPMap), len(ann.Stages))
	log.Printf("[FlowAnnotations] ========== CALLING LLM FOR ANNOTATIONS END (success) ==========")
	return ann
}

// parseFlowAnnotationsJSON parses and validates the LLM JSON response into FlowAnnotationsV1.
// validFrameNumbers is a set of valid frame.number strings from input packets.
// It filters stage frames to only include valid frame numbers and removes stages with no valid frames.
func parseFlowAnnotationsJSON(response string, validFrameNumbers map[string]bool) (*FlowAnnotationsV1, error) {
	log.Printf("[FlowAnnotationsParse] ========== PARSING ANNOTATIONS JSON START ==========")
	log.Printf("[FlowAnnotationsParse] Response length: %d bytes, valid frame numbers: %d", len(response), len(validFrameNumbers))

	// Try to extract JSON from response (in case LLM added extra text)
	jsonStr := extractJSONFromResponse(response)
	if jsonStr == "" {
		log.Printf("[FlowAnnotationsParse] ERROR: No JSON object found in response")
		log.Printf("[FlowAnnotationsParse] Response preview: %s", truncateForLog(response, 500))
		return nil, fmt.Errorf("no JSON object found in response")
	}
	log.Printf("[FlowAnnotationsParse] Extracted JSON: length=%d bytes", len(jsonStr))

	var ann FlowAnnotationsV1
	if err := json.Unmarshal([]byte(jsonStr), &ann); err != nil {
		log.Printf("[FlowAnnotationsParse] ERROR: JSON unmarshal failed: %v", err)
		log.Printf("[FlowAnnotationsParse] JSON preview: %s", truncateForLog(jsonStr, 500))
		return nil, fmt.Errorf("json unmarshal failed: %w", err)
	}
	log.Printf("[FlowAnnotationsParse] JSON unmarshaled successfully")

	// Validate version
	if ann.Version != "flow_annotations_v1" && ann.Version != "" {
		log.Printf("[FlowAnnotationsParse] Warning: unexpected version %q, proceeding anyway", ann.Version)
	}
	ann.Version = "flow_annotations_v1"

	// Default flow_name
	if ann.FlowName == "" {
		ann.FlowName = "信令流程图"
		log.Printf("[FlowAnnotationsParse] Using default flow_name: %s", ann.FlowName)
	} else {
		log.Printf("[FlowAnnotationsParse] Parsed flow_name: %s", ann.FlowName)
	}

	// Log IP map details
	log.Printf("[FlowAnnotationsParse] IP Map (before dedup): %d entries", len(ann.IPMap))
	for i, m := range ann.IPMap {
		log.Printf("[FlowAnnotationsParse]   IPMap[%d]: ip=%s, ne=%s, confidence=%.2f, reason=%s",
			i, m.IP, m.NE, m.Confidence, safeOneLine(m.Reason, 60))
	}

	// Deduplicate IP map (keep last entry for each IP)
	ann.IPMap = deduplicateIPMap(ann.IPMap)
	log.Printf("[FlowAnnotationsParse] IP Map (after dedup): %d entries", len(ann.IPMap))

	// Log stages before filtering
	log.Printf("[FlowAnnotationsParse] Stages (before filter): %d stages", len(ann.Stages))
	totalFramesBefore := 0
	for i, s := range ann.Stages {
		totalFramesBefore += len(s.Frames)
		log.Printf("[FlowAnnotationsParse]   Stage[%d]: name=%q, frames=%d, summary=%q",
			i, s.Name, len(s.Frames), safeOneLine(s.Summary, 60))
		// Log first few frames of each stage
		previewCount := len(s.Frames)
		if previewCount > 5 {
			previewCount = 5
		}
		for j := 0; j < previewCount; j++ {
			f := s.Frames[j]
			log.Printf("[FlowAnnotationsParse]     Frame[%d]: number=%s, title=%q, note=%q",
				j, f.Number, safeOneLine(f.Title, 40), safeOneLine(f.Note, 40))
		}
		if len(s.Frames) > 5 {
			log.Printf("[FlowAnnotationsParse]     ... (%d more frames)", len(s.Frames)-5)
		}
	}
	log.Printf("[FlowAnnotationsParse] Total frames before filter: %d", totalFramesBefore)

	// Validate and filter stage frames
	ann.Stages = validateAndFilterStageFrames(ann.Stages, validFrameNumbers)

	// Check if we have any valid frames across all stages
	totalFrames := 0
	for _, s := range ann.Stages {
		totalFrames += len(s.Frames)
	}

	log.Printf("[FlowAnnotationsParse] Stages (after filter): %d stages, total frames: %d", len(ann.Stages), totalFrames)
	if totalFrames == 0 {
		log.Printf("[FlowAnnotationsParse] ERROR: No valid frames found after filtering")
		return nil, fmt.Errorf("no valid frames found in any stage")
	}

	// Log final stage summary
	for i, s := range ann.Stages {
		log.Printf("[FlowAnnotationsParse]   FinalStage[%d]: name=%q, frames=%d", i, s.Name, len(s.Frames))
	}

	log.Printf("[FlowAnnotationsParse] ========== PARSING ANNOTATIONS JSON END ==========")
	log.Printf("[FlowAnnotationsParse] Result: flow_name=%q, ip_map=%d, stages=%d, total_frames=%d",
		ann.FlowName, len(ann.IPMap), len(ann.Stages), totalFrames)

	return &ann, nil
}

// extractJSONFromResponse tries to extract a JSON object from the response.
// Handles cases where LLM might wrap it in markdown code blocks or add extra text.
func extractJSONFromResponse(response string) string {
	response = strings.TrimSpace(response)

	// If response starts with {, assume it's raw JSON
	if strings.HasPrefix(response, "{") {
		// Find matching closing brace
		depth := 0
		for i, c := range response {
			if c == '{' {
				depth++
			} else if c == '}' {
				depth--
				if depth == 0 {
					return response[:i+1]
				}
			}
		}
		return response // Return as-is, let json.Unmarshal handle errors
	}

	// Try to find JSON in markdown code block
	if idx := strings.Index(response, "```json"); idx != -1 {
		start := idx + len("```json")
		if endIdx := strings.Index(response[start:], "```"); endIdx != -1 {
			return strings.TrimSpace(response[start : start+endIdx])
		}
	}

	// Try to find JSON in generic code block
	if idx := strings.Index(response, "```"); idx != -1 {
		start := idx + len("```")
		// Skip optional language tag
		if nlIdx := strings.Index(response[start:], "\n"); nlIdx != -1 {
			start += nlIdx + 1
		}
		if endIdx := strings.Index(response[start:], "```"); endIdx != -1 {
			candidate := strings.TrimSpace(response[start : start+endIdx])
			if strings.HasPrefix(candidate, "{") {
				return candidate
			}
		}
	}

	// Try to find { ... } anywhere in the response
	if idx := strings.Index(response, "{"); idx != -1 {
		depth := 0
		for i := idx; i < len(response); i++ {
			if response[i] == '{' {
				depth++
			} else if response[i] == '}' {
				depth--
				if depth == 0 {
					return response[idx : i+1]
				}
			}
		}
	}

	return ""
}

// deduplicateIPMap removes duplicate IP entries, keeping the last (or highest confidence) one.
func deduplicateIPMap(ipMap []IPMapping) []IPMapping {
	if len(ipMap) == 0 {
		return ipMap
	}

	seen := make(map[string]int) // ip -> index in result
	result := make([]IPMapping, 0, len(ipMap))

	for _, m := range ipMap {
		ip := strings.TrimSpace(m.IP)
		if ip == "" {
			continue
		}
		m.IP = ip
		m.NE = normalizeNEType(m.NE)

		if existingIdx, ok := seen[ip]; ok {
			// Keep the one with higher confidence, or the new one if confidence is equal/higher
			if m.Confidence >= result[existingIdx].Confidence {
				result[existingIdx] = m
			}
		} else {
			seen[ip] = len(result)
			result = append(result, m)
		}
	}

	return result
}

// normalizeNEType normalizes network element type names.
func normalizeNEType(ne string) string {
	ne = strings.TrimSpace(ne)
	upper := strings.ToUpper(ne)

	// Normalize common variations
	switch upper {
	case "GNB", "ENB", "GNODEB", "ENODEB":
		if strings.HasPrefix(upper, "E") {
			return "eNB"
		}
		return "gNB"
	case "AMF", "MME", "SMF", "UPF", "SGW", "PGW", "HSS", "UDM", "AUSF", "PCRF":
		return upper
	case "S-GW", "SGW-C", "SGW-U":
		return "SGW"
	case "P-GW", "PGW-C", "PGW-U":
		return "PGW"
	case "UNKNOWN", "":
		return "Unknown"
	default:
		return ne // Keep original if not recognized
	}
}

// validateAndFilterStageFrames validates stage frames against valid frame numbers.
// Removes frames with invalid numbers, deduplicates, and removes stages with no valid frames.
// validFrameNumbers is a set of valid frame.number strings from input packets.
func validateAndFilterStageFrames(stages []FlowStage, validFrameNumbers map[string]bool) []FlowStage {
	if len(stages) == 0 {
		return nil
	}

	result := make([]FlowStage, 0, len(stages))

	for _, s := range stages {
		name := strings.TrimSpace(s.Name)
		if name == "" {
			continue
		}
		s.Name = name
		s.Summary = strings.TrimSpace(s.Summary)

		// Filter and deduplicate frames
		seen := make(map[string]bool)
		validFrames := make([]FlowStageFrame, 0, len(s.Frames))
		for _, f := range s.Frames {
			num := strings.TrimSpace(f.Number)
			if num == "" {
				continue
			}
			// Check if frame number exists in input
			if !validFrameNumbers[num] {
				continue
			}
			// Deduplicate
			if seen[num] {
				continue
			}
			seen[num] = true

			validFrames = append(validFrames, FlowStageFrame{
				Number: num,
				Title:  strings.TrimSpace(f.Title),
				Note:   strings.TrimSpace(f.Note),
			})
		}

		// Skip stage if no valid frames
		if len(validFrames) == 0 {
			continue
		}
		s.Frames = validFrames

		result = append(result, s)
	}

	return result
}

// collectAllFrameNumbers collects all unique frame numbers from all stages.
// Returns the frame numbers in the order they first appear across all stages.
func collectAllFrameNumbers(stages []FlowStage) []string {
	seen := make(map[string]bool)
	result := make([]string, 0)

	for _, s := range stages {
		for _, f := range s.Frames {
			if !seen[f.Number] {
				seen[f.Number] = true
				result = append(result, f.Number)
			}
		}
	}

	return result
}

// filterPacketsByFrameNumbers filters packets to only include those with frame.number in selectedFrames.
// Returns the filtered packets JSON (maintaining original order) and the count.
// If selectedFrames is empty, returns the original JSON unchanged.
func filterPacketsByFrameNumbers(compactJSON string, selectedFrames map[string]bool) (string, int, error) {
	if len(selectedFrames) == 0 {
		// Return original
		var packets []map[string]interface{}
		if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
			return compactJSON, 0, err
		}
		return compactJSON, len(packets), nil
	}

	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(compactJSON), &packets); err != nil {
		return "", 0, fmt.Errorf("failed to parse JSON: %w", err)
	}

	filtered := make([]map[string]interface{}, 0, len(selectedFrames))
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok {
				if selectedFrames[num] {
					filtered = append(filtered, pkt)
				}
			}
		}
	}

	result, err := json.Marshal(filtered)
	if err != nil {
		return "", 0, fmt.Errorf("failed to marshal filtered packets: %w", err)
	}

	return string(result), len(filtered), nil
}

// collectSelectedFramesSet collects all unique frame numbers from stages into a set.
func collectSelectedFramesSet(stages []FlowStage) map[string]bool {
	result := make(map[string]bool)
	for _, s := range stages {
		for _, f := range s.Frames {
			result[f.Number] = true
		}
	}
	return result
}

// truncateForLog truncates a string for logging purposes.
func truncateForLog(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}

// participantInfo holds parsed info about a participant for sorting
type participantInfo struct {
	FullName   string // e.g., "AMF(10.18.11.20)"
	Role       string // e.g., "AMF"
	IP         string // e.g., "10.18.11.20"
	FirstSeen  int    // order of first appearance
	GroupIndex int    // index in roleOrder for sorting
}

// roleOrder defines the fixed ordering of network element roles.
// gNB* → AMF* → SMF* → UPF* → other NEs
var roleOrder = []string{"gNB", "eNB", "AMF", "MME", "SMF", "PGW", "UPF", "SGW"}

// getRoleGroupIndex returns the index in roleOrder for a given role, or a large number for unknown roles.
func getRoleGroupIndex(role string) int {
	for i, r := range roleOrder {
		if strings.EqualFold(role, r) {
			return i
		}
	}
	return len(roleOrder) // Unknown roles go at the end
}

// parseParticipantName extracts role and IP from a participant name like "AMF(10.18.11.20)"
func parseParticipantName(name string) (role, ip string) {
	if idx := strings.Index(name, "("); idx != -1 {
		role = name[:idx]
		if endIdx := strings.Index(name, ")"); endIdx > idx {
			ip = name[idx+1 : endIdx]
		}
	} else {
		role = name
	}
	return
}

// sortAndNumberParticipants sorts participants by role group order and numbers duplicates.
// Order: gNB* → AMF* → SMF* → UPF* → others
// Same role with multiple IPs get numbered: gNB1(10.x), gNB2(10.y)
func sortAndNumberParticipants(participants []string) []string {
	if len(participants) == 0 {
		return participants
	}

	// Parse all participants
	infos := make([]participantInfo, len(participants))
	for i, p := range participants {
		role, ip := parseParticipantName(p)
		infos[i] = participantInfo{
			FullName:   p,
			Role:       role,
			IP:         ip,
			FirstSeen:  i,
			GroupIndex: getRoleGroupIndex(role),
		}
	}

	// Sort by group index, then by first seen order within group
	sort.SliceStable(infos, func(i, j int) bool {
		if infos[i].GroupIndex != infos[j].GroupIndex {
			return infos[i].GroupIndex < infos[j].GroupIndex
		}
		return infos[i].FirstSeen < infos[j].FirstSeen
	})

	// Number duplicates within same role
	roleCounts := make(map[string]int)
	for _, info := range infos {
		roleCounts[info.Role]++
	}

	result := make([]string, len(infos))
	roleSeq := make(map[string]int) // current sequence number for each role

	for i, info := range infos {
		if roleCounts[info.Role] > 1 {
			// Multiple instances of this role - add number
			roleSeq[info.Role]++
			seq := roleSeq[info.Role]
			if info.IP != "" {
				result[i] = fmt.Sprintf("%s%d(%s)", info.Role, seq, info.IP)
			} else {
				result[i] = fmt.Sprintf("%s%d", info.Role, seq)
			}
		} else {
			// Single instance - keep original name
			result[i] = info.FullName
		}
	}

	return result
}

// LLMMappingEntry represents a single idx:frameNumber mapping from LLM output
type LLMMappingEntry struct {
	Idx         int    `json:"idx"`
	FrameNumber string `json:"frame_number"`
}

type flowLLMParsed struct {
	FlowName string
	Mermaid  string
	Mapping  []LLMMappingEntry // New: LLM-provided mapping of autonumber idx to frame.number
}

// parseFlowLLMResponse extracts FLOW_NAME, MERMAID, and MAPPING from the LLM response.
// MAPPING section provides the correlation between Mermaid autonumber and original frame.number.
func parseFlowLLMResponse(response string) flowLLMParsed {
	log.Printf("[FlowParse] ========== PARSING LLM RESPONSE START ==========")
	log.Printf("[FlowParse] Response length: %d bytes", len(response))

	response = strings.TrimSpace(response)

	out := flowLLMParsed{FlowName: "信令流程图"}

	// Check for key markers
	hasFlowName := strings.Contains(response, "---FLOW_NAME---")
	hasMermaid := strings.Contains(response, "---MERMAID---")
	hasMapping := strings.Contains(response, "---MAPPING---")
	hasPacketList := strings.Contains(response, "---PACKET_LIST---")
	hasMermaidBlock := strings.Contains(response, "```mermaid")
	hasSequenceDiagram := strings.Contains(response, "sequenceDiagram")

	log.Printf("[FlowParse] Markers detected: FLOW_NAME=%v, MERMAID=%v, MAPPING=%v, PACKET_LIST=%v, mermaid_block=%v, sequenceDiagram=%v",
		hasFlowName, hasMermaid, hasMapping, hasPacketList, hasMermaidBlock, hasSequenceDiagram)

	// FLOW_NAME
	if idx := strings.Index(response, "---FLOW_NAME---"); idx != -1 {
		rest := response[idx+len("---FLOW_NAME---"):]
		if endIdx := strings.Index(rest, "---"); endIdx != -1 {
			out.FlowName = strings.TrimSpace(rest[:endIdx])
			log.Printf("[FlowParse] Extracted FLOW_NAME: %s", out.FlowName)
		}
	}

	// MERMAID (stop at MAPPING or other markers)
	var mermaidCode string
	if idx := strings.Index(response, "---MERMAID---"); idx != -1 {
		rest := strings.TrimSpace(response[idx+len("---MERMAID---"):])
		// Stop at MAPPING marker (new format)
		if mIdx := strings.Index(rest, "---MAPPING---"); mIdx != -1 {
			mermaidCode = strings.TrimSpace(rest[:mIdx])
		} else if dIdx := strings.Index(rest, "---DETAILS---"); dIdx != -1 {
			// Stop at DETAILS marker (backward compatibility)
			mermaidCode = strings.TrimSpace(rest[:dIdx])
		} else if dIdx := strings.Index(rest, "---"); dIdx != -1 {
			// Stop at any other marker
			mermaidCode = strings.TrimSpace(rest[:dIdx])
		} else {
			mermaidCode = strings.TrimSpace(rest)
		}
	} else if idx := strings.Index(response, "```mermaid"); idx != -1 {
		rest := response[idx+len("```mermaid"):]
		if endIdx := strings.Index(rest, "```"); endIdx != -1 {
			mermaidCode = strings.TrimSpace(rest[:endIdx])
		} else {
			mermaidCode = strings.TrimSpace(rest)
		}
	} else if idx := strings.Index(response, "sequenceDiagram"); idx != -1 {
		mermaidCode = strings.TrimSpace(response[idx:])
	} else {
		mermaidCode = response
	}

	// Clean up any trailing markdown from Mermaid
	if idx := strings.LastIndex(mermaidCode, "```"); idx != -1 {
		mermaidCode = strings.TrimSpace(mermaidCode[:idx])
	}
	out.Mermaid = mermaidCode
	log.Printf("[FlowParse] Extracted MERMAID: length=%d bytes", len(mermaidCode))

	// Count message lines in Mermaid
	mermaidMsgCount := countMermaidMessages(mermaidCode)
	log.Printf("[FlowParse] Mermaid diagram message count: %d", mermaidMsgCount)

	// Log first few lines of Mermaid for debugging
	mermaidLines := strings.Split(mermaidCode, "\n")
	previewLines := mermaidLines
	if len(previewLines) > 10 {
		previewLines = previewLines[:10]
	}
	log.Printf("[FlowParse] Mermaid preview (first %d lines):", len(previewLines))
	for i, line := range previewLines {
		log.Printf("[FlowParse]   [%d] %s", i+1, safeOneLine(line, 100))
	}
	if len(mermaidLines) > 10 {
		log.Printf("[FlowParse]   ... (%d more lines)", len(mermaidLines)-10)
	}

	// Parse MAPPING section (new format: idx:frameNumber per line)
	if idx := strings.Index(response, "---MAPPING---"); idx != -1 {
		rest := strings.TrimSpace(response[idx+len("---MAPPING---"):])
		// Find end of mapping section (next --- or end of string)
		endIdx := len(rest)
		if dIdx := strings.Index(rest, "---"); dIdx != -1 {
			endIdx = dIdx
		}
		mappingSection := strings.TrimSpace(rest[:endIdx])
		log.Printf("[FlowParse] Found MAPPING section: length=%d bytes", len(mappingSection))

		// Parse each line: format is "idx:frameNumber"
		lines := strings.Split(mappingSection, "\n")
		validMappings := 0
		invalidMappings := 0
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line == "" {
				continue
			}
			parts := strings.SplitN(line, ":", 2)
			if len(parts) != 2 {
				invalidMappings++
				continue
			}
			idxStr := strings.TrimSpace(parts[0])
			frameStr := strings.TrimSpace(parts[1])

			idx, err := strconv.Atoi(idxStr)
			if err != nil {
				invalidMappings++
				continue
			}

			out.Mapping = append(out.Mapping, LLMMappingEntry{
				Idx:         idx,
				FrameNumber: frameStr,
			})
			validMappings++
		}
		log.Printf("[FlowParse] Parsed MAPPING: valid=%d, invalid=%d", validMappings, invalidMappings)
	} else {
		log.Printf("[FlowParse] No MAPPING section found in response")
	}

	log.Printf("[FlowParse] ========== PARSING LLM RESPONSE END ==========")
	log.Printf("[FlowParse] Result: flow_name=%q, mermaid_len=%d, mapping_entries=%d",
		out.FlowName, len(out.Mermaid), len(out.Mapping))

	return out
}

// GenerateFlowStream handles POST /api/jobs/{id}/flow/generate/stream
// Uses Server-Sent Events to stream the LLM response in real-time.
// LLM only returns structured annotations (IP→NE mapping, stages);
// Mermaid is always generated deterministically by Go.
func (h *Handler) GenerateFlowStream(w http.ResponseWriter, r *http.Request) {
	startTime := time.Now()
	id := r.PathValue("id")

	log.Printf("[FlowGenerateStream] ========== STREAM FLOW GENERATION START ==========")
	log.Printf("[FlowGenerateStream] Job ID: %s", id)

	job, ok := h.jobMgr.GetJob(id)
	if !ok {
		log.Printf("[FlowGenerateStream] ERROR: Job not found: %s", id)
		writeError(w, http.StatusNotFound, "job not found")
		return
	}

	var req FlowGenerateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		log.Printf("[FlowGenerateStream] ERROR: Invalid request body: %v", err)
		writeError(w, http.StatusBadRequest, fmt.Sprintf("invalid request body: %v", err))
		return
	}

	log.Printf("[FlowGenerateStream] Request: filter=%q, max_events=%d", req.Filter, req.MaxEvents)

	if req.Filter == "" {
		log.Printf("[FlowGenerateStream] ERROR: Filter is required")
		writeError(w, http.StatusBadRequest, "filter is required")
		return
	}

	maxPackets := req.MaxEvents
	if maxPackets <= 0 {
		maxPackets = 200
	}
	log.Printf("[FlowGenerateStream] Using maxPackets=%d", maxPackets)

	// Set up SSE headers
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	flusher, ok := w.(http.Flusher)
	if !ok {
		writeError(w, http.StatusInternalServerError, "streaming not supported")
		return
	}

	// Helper to send SSE event
	sendEvent := func(event, data string) {
		fmt.Fprintf(w, "event: %s\ndata: %s\n\n", event, data)
		flusher.Flush()
	}

	// Get cached text or generate new (same data source as "复制JSON" button)
	cacheKey := generateTextCacheKey(req.Filter)
	var compactJSON string
	if cached, ok := h.jobMgr.GetCachedTextExport(id, cacheKey); ok {
		compactJSON = cached
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		result, err := tshark.TsharkCompactJSON(ctx, job.MergedPcap, req.Filter, applicationProtocols)
		if err != nil {
			sendEvent("error", fmt.Sprintf(`{"message":"failed to get packets: %s"}`, err.Error()))
			return
		}
		if result.ExitCode != 0 {
			sendEvent("error", fmt.Sprintf(`{"message":"tshark error: %s"}`, strings.TrimSpace(result.Stderr)))
			return
		}

		var err2 error
		compactJSON, err2 = packet.SimplifyPacketsJSON(result.Stdout)
		if err2 != nil {
			compactJSON = result.Stdout
		}
		h.jobMgr.CacheTextExport(id, cacheKey, compactJSON)
	}

	// Limit the number of packets sent to LLM if needed
	limitedJSON, _, err := limitPacketsJSON(compactJSON, maxPackets)
	if err != nil {
		sendEvent("error", fmt.Sprintf(`{"message":"failed to process packets: %s"}`, err.Error()))
		return
	}

	// Extract key params from compactJSON
	keyParams := extractKeyParamsFromJSON(compactJSON)

	// Filter heartbeat packets so LLM input is deterministic and correlation is absolute.
	llmInputJSON, removedHeartbeats, err := filterHeartbeatPacketsJSON(limitedJSON)
	if err != nil {
		llmInputJSON = limitedJSON
		removedHeartbeats = 0
	}

	// Count packets in llmInputJSON and build valid frame numbers set
	var packets []map[string]interface{}
	if err := json.Unmarshal([]byte(llmInputJSON), &packets); err != nil {
		sendEvent("error", fmt.Sprintf(`{"message":"failed to parse packets: %s"}`, err.Error()))
		return
	}
	packetCount := len(packets)

	// Build valid frame numbers set
	validFrameNumbers := make(map[string]bool)
	for _, pkt := range packets {
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			if num, ok := frame["number"].(string); ok && num != "" {
				validFrameNumbers[num] = true
			}
		}
	}

	log.Printf("[FlowGenerateStream] Packet processing: total=%d, removed_heartbeats=%d, final=%d",
		packetCount+removedHeartbeats, removedHeartbeats, packetCount)

	// Log input packets summary
	log.Printf("[FlowGenerateStream] Input packets summary (%d packets):", packetCount)
	previewCount := packetCount
	if previewCount > 8 {
		previewCount = 8
	}
	for i := 0; i < previewCount; i++ {
		pkt := packets[i]
		frameNum := ""
		if frame, ok := pkt["frame"].(map[string]interface{}); ok {
			frameNum = getString(frame, "number")
		}
		proto := ""
		msgType := ""
		if app, ok := pkt["application"].(map[string]interface{}); ok {
			for protoName, protoData := range app {
				proto = protoName
				if pd, ok := protoData.(map[string]interface{}); ok {
					if procedure, ok := pd["procedure"].(string); ok {
						msgType = procedure
					} else if message, ok := pd["message"].(string); ok {
						msgType = message
					} else if mmMsg, ok := pd["mm_message"].(string); ok {
						msgType = mmMsg
					}
				}
				break
			}
		}
		log.Printf("[FlowGenerateStream]   [%d] frame=%s, proto=%s, msg=%s",
			i+1, frameNum, proto, safeOneLine(msgType, 50))
	}
	if packetCount > 8 {
		log.Printf("[FlowGenerateStream]   ... (%d more packets)", packetCount-8)
	}

	// Send key params first
	if keyParams != nil {
		keyParamsJSON, _ := json.Marshal(keyParams)
		sendEvent("key_params", string(keyParamsJSON))
		log.Printf("[FlowGenerateStream] Sent key_params event")
	}

	// Send input_json for frontend to derive rich details from original packets
	inputJSONEscaped, err := json.Marshal(llmInputJSON)
	if err != nil {
		log.Printf("[FlowGenerateStream] ERROR: Failed to marshal input_json: %v", err)
	} else {
		escapedStr := string(inputJSONEscaped)
		log.Printf("[FlowGenerateStream] Sending input_json: size=%d bytes", len(escapedStr))
		sendEvent("input_json", escapedStr)
	}

	// Build and send details_map (idx->originNumber mapping) for frontend correlation
	// This is always sequential (1:1 with packets) since Go generates Mermaid deterministically
	detailsMap := buildDetailsMapping(llmInputJSON)
	detailsMapJSON, _ := json.Marshal(detailsMap)
	sendEvent("details_map", string(detailsMapJSON))
	log.Printf("[FlowGenerateStream] Sent details_map: %d entries", len(detailsMap))

	// Check Moonshot client
	client := h.getMoonshotClient()
	if client == nil {
		// No LLM configured - generate Mermaid without annotations
		log.Printf("[FlowGenerateStream] Moonshot API key not configured, generating Mermaid without annotations")
		flowName := "信令流程图"
		mermaid := buildDeterministicMermaid(llmInputJSON, flowName, nil)
		log.Printf("[FlowGenerateStream] Generated deterministic Mermaid: length=%d bytes", len(mermaid))
		finalEvent := FlowFinalEvent{
			FlowName:    flowName,
			Mermaid:     mermaid,
			Details:     detailsMap,
			Mode:        "go_deterministic",
			Annotations: nil,
		}
		finalJSON, _ := json.Marshal(finalEvent)
		sendEvent("flow_final", string(finalJSON))
		sendEvent("done", `{"status":"completed"}`)
		elapsed := time.Since(startTime)
		log.Printf("[FlowGenerateStream] Completed without LLM in %v", elapsed)
		log.Printf("[FlowGenerateStream] ========== STREAM FLOW GENERATION END (no LLM) ==========")
		return
	}

	// Build prompt for annotations only (not Mermaid)
	prompt := buildFlowAnnotationsPrompt(llmInputJSON, packetCount)
	log.Printf("[FlowGenerateStream] Built annotations prompt: size=%d bytes", len(prompt))
	log.Printf("[FlowGenerateStream] Starting LLM stream call...")

	ctx, cancel := context.WithTimeout(r.Context(), 3*time.Minute)
	defer cancel()

	// Stream the response (LLM outputs JSON annotations)
	llmStartTime := time.Now()
	var fullResp strings.Builder
	chunkCount := 0
	err = client.ChatCompletionStream(ctx, prompt, func(chunk string) error {
		chunkCount++
		fullResp.WriteString(chunk)
		// Stream chunks to frontend for live display
		chunkJSON, _ := json.Marshal(chunk)
		sendEvent("chunk", string(chunkJSON))
		return nil
	})
	llmElapsed := time.Since(llmStartTime)
	log.Printf("[FlowGenerateStream] LLM stream completed in %v, received %d chunks, total response: %d bytes",
		llmElapsed, chunkCount, fullResp.Len())

	var annotations *FlowAnnotationsV1
	if err != nil {
		log.Printf("[FlowGenerateStream] LLM stream error: %v", err)
		log.Printf("[FlowGenerateStream] Will generate Mermaid without annotations (fallback mode)")
		// Don't fail - we can still generate Mermaid without annotations
	} else {
		// Log raw LLM response
		rawResp := fullResp.String()
		log.Printf("[FlowGenerateStream] Raw LLM response preview: %s", truncateForLog(rawResp, 600))
		if len(rawResp) > 600 {
			log.Printf("[FlowGenerateStream] Raw LLM response (last 300 chars): ...%s", rawResp[len(rawResp)-300:])
		}

		// Parse annotations from LLM response
		log.Printf("[FlowGenerateStream] Parsing annotations from LLM response...")
		annotations, err = parseFlowAnnotationsJSON(rawResp, validFrameNumbers)
		if err != nil {
			log.Printf("[FlowGenerateStream] PARSE FAILED: %v", err)
			log.Printf("[FlowGenerateStream] Will generate Mermaid without annotations (fallback mode)")
		} else {
			log.Printf("[FlowGenerateStream] PARSE SUCCESS: flow_name=%q, ip_map=%d, stages=%d",
				annotations.FlowName, len(annotations.IPMap), len(annotations.Stages))
			// Log parsed annotations summary
			for i, m := range annotations.IPMap {
				log.Printf("[FlowGenerateStream]   IPMap[%d]: %s -> %s (conf=%.2f)", i, m.IP, m.NE, m.Confidence)
			}
			totalStageFrames := 0
			for i, s := range annotations.Stages {
				totalStageFrames += len(s.Frames)
				log.Printf("[FlowGenerateStream]   Stage[%d]: %q (%d frames)", i, s.Name, len(s.Frames))
			}
			log.Printf("[FlowGenerateStream]   Total stage frames: %d", totalStageFrames)
		}
	}

	// Determine which JSON to use for rendering
	// If annotations are valid, filter to only selected frames (subset rendering)
	renderJSON := llmInputJSON
	flowName := "信令流程图"

	if annotations != nil {
		flowName = annotations.FlowName
		// Collect selected frames from all stages
		selectedFrames := collectSelectedFramesSet(annotations.Stages)
		log.Printf("[FlowGenerateStream] Selected frames from annotations: %d frames", len(selectedFrames))
		if len(selectedFrames) > 0 {
			filteredJSON, filteredCount, filterErr := filterPacketsByFrameNumbers(llmInputJSON, selectedFrames)
			if filterErr != nil {
				log.Printf("[FlowGenerateStream] Warning: failed to filter packets, using full set: %v", filterErr)
			} else if filteredCount > 0 {
				renderJSON = filteredJSON
				log.Printf("[FlowGenerateStream] Filtered packets: %d -> %d (based on annotations)", packetCount, filteredCount)
			}
		}
	}

	// Generate Mermaid deterministically from Go using annotations
	log.Printf("[FlowGenerateStream] Generating deterministic Mermaid diagram...")
	mermaid := buildDeterministicMermaid(renderJSON, flowName, annotations)
	log.Printf("[FlowGenerateStream] Generated Mermaid: length=%d bytes", len(mermaid))

	// Log Mermaid preview
	mermaidLines := strings.Split(mermaid, "\n")
	previewLineCount := len(mermaidLines)
	if previewLineCount > 10 {
		previewLineCount = 10
	}
	log.Printf("[FlowGenerateStream] Mermaid preview (first %d lines):", previewLineCount)
	for i := 0; i < previewLineCount; i++ {
		log.Printf("[FlowGenerateStream]   [%d] %s", i+1, safeOneLine(mermaidLines[i], 80))
	}
	if len(mermaidLines) > 10 {
		log.Printf("[FlowGenerateStream]   ... (%d more lines)", len(mermaidLines)-10)
	}

	// Build details mapping from the render JSON (guaranteed 1:1 with Mermaid)
	finalDetailsMap := buildDetailsMapping(renderJSON)
	log.Printf("[FlowGenerateStream] Built final details mapping: %d entries", len(finalDetailsMap))

	// Build stats
	stats := FlowValidationStats{
		InputPackets:      packetCount,
		MermaidMessages:   len(finalDetailsMap),
		MappingEntries:    len(finalDetailsMap),
		RemovedHeartbeats: removedHeartbeats,
	}
	log.Printf("[FlowGenerateStream] Stats: input=%d, mermaid_msgs=%d, mapping=%d, removed_heartbeats=%d",
		stats.InputPackets, stats.MermaidMessages, stats.MappingEntries, stats.RemovedHeartbeats)

	finalEvent := FlowFinalEvent{
		FlowName:    flowName,
		Mermaid:     mermaid,
		Details:     finalDetailsMap,
		Mode:        "go_deterministic",
		Stats:       &stats,
		Annotations: annotations,
	}
	finalJSON, _ := json.Marshal(finalEvent)
	sendEvent("flow_final", string(finalJSON))
	log.Printf("[FlowGenerateStream] Sent flow_final event: %d bytes", len(finalJSON))

	// Also send the updated input_json that matches the diagram
	updatedInputJSON, _ := json.Marshal(renderJSON)
	sendEvent("input_json_final", string(updatedInputJSON))
	log.Printf("[FlowGenerateStream] Sent input_json_final event: %d bytes", len(updatedInputJSON))

	// Send done event after flow_final so frontend can render validated content.
	sendEvent("done", `{"status":"completed"}`)

	elapsed := time.Since(startTime)
	log.Printf("[FlowGenerateStream] ========== STREAM FLOW GENERATION END (success) ==========")
	log.Printf("[FlowGenerateStream] Completed in %v: flow_name=%q, annotations=%v, mermaid_messages=%d",
		elapsed, flowName, annotations != nil, len(finalDetailsMap))
}
